### ISSUE TITLE
02_end_to_end_machine_learning_project.ipynb -- TypeError: object supporting the buffer API required

### ISSUE THREAD

**Issue by thiagoavadore** [ageron/handson-ml#1]
Hi, ageron!

Great book! I am using the notebooks and trying to understand properly everything. Therefore I forked and I will submite some PR's soon... but this one I couldn't solve. On `02_end_to_end_machine_learning_project.ipynb` there is a part where you do the split by the hash of each instance’s identifier with this function. I am not able to make this function work because it is throwing the following error:

~~~~
----> 4     return hash(identifier).digest()[-1] < 256 * test_ratio
          5                                                                                              
          6 def split_train_test_by_id(data, test_ratio, id_column, hash=hashlib.md5):
          TypeError: object supporting the buffer API required
~~~~

Thanks for the book and I will keep reading on the early-release!

**Comment by ageron** [comment]
Hi Thiago,

Thanks for your kind words and for your feedback.  I just checked, I get the same error as you. It seems that `identifier` used to be a string and somehow it is now an `int`. Weird, probably a change I made, sorry about that. Anyway, the fix is simple (I just pushed it): replace `hash(identifier)` by `hash(str(identifier).encode("ascii"))`.  Basically MD5 only works on a byte array (on another object that implements the buffer API). So I first convert the int to a string, then encode the string to a byte array. No pretty, but it works.

**Comment by ageron** [comment]
Apparently what happened is that in a previous version of Pandas, integers were returned as numpy.int64, which happen to implement the buffer API.  Now they are returned as plain ints, hence the bug.  This led me to a cleaner solution: simply convert the identifier to a numpy.int64, and the bug is fixed.  It beats converting it to a unicode string then encoding it to ascii.

Side note: I wrote this chapter using scikit-learn 0.17.1, and you will get a bunch of deprecation warnings right now if you run it using the latest scikit-learn version 0.18.  I'm going through the code now to get rid of these warnings. It's hard to write a book on a moving target!

**Comment by thiagoavadore** [comment]
Thanks very much for the Help! =)

**Comment by ageron** [comment]
My pleasure.  FYI, I upgraded all notebooks to sklearn 0.18, so the deprecated warnings are gone.  Don't hesitate to mention all problems you run into, I can still fix the book in the next couple of weeks. Thanks!
