### ISSUE TITLE
Source code organization

### ISSUE THREAD

**Issue by hrseymour** [ageron/handson-ml#101]
I am just starting the book, and am already frustrated by Example 1-1.  Its source code is not on Github as a separate file.  I hunted around and found it in the middle of the Jupyter file 01_the_machine_learning_landscape.ipynb.  Am I going to have to hunt for all of the examples in this way?

Also, I don't want to run Jupyter.  I wish .py files were provided for all examples.

**Comment by ChapelHeel66** [comment]
It's just an example in the overview to "whet your appetite," as the book says.  See also footnote 7, where it tells you that everything is going to be explained later.  

I don't think the author intends for you to type in Example 1-1, or even download it and run it.  It's just setting the stage for what's coming later, and all the code is provided on Github for all the later stuff.

**Comment by ageron** [comment]
Hi @hrseymour ,

Thanks for your feedback.  As @ChapelHeel66 kindly pointed out, the code example in the first chapter is really only there to give you a general idea of where you are going.  You are going to go into all of the details in chapter 2, and hopefully you won't have much trouble following along from there on. There are plenty of steps before training a machine learning model, and I did not want to drown the reader with these details in chapter 1, so that's why the code example is not right at the beginning of the notebook (the beginning loads and preprocesses the data).  In the rest of the book, you should have no trouble following along, even though there are many cells that I left out of the book (either because they were repetitive or because they were not the focus of the chapter, such as details of how to create matplotlib figures).
 
I could make all the examples available as separate .py files, but it's not necessary since Jupyter lets you download the code as a .py (File > Download > Python).  If you do, you might have to configure Matplotlib backend so that it knows where to plot the figures, but other than that everything should work fine.  However, I recommend using Jupyter: it's great for playing around with examples, tweaking them, viewing the results immediately, etc.

I hope you will feel better once you go through chapter 2 (and beyond).

**Comment by ageron** [comment]
Hi @hrseymour ,
Closing this issue, please reopen if you have any further questions.  I hope you are enjoying the book.
Cheers
