### ISSUE TITLE
Chapter2 Housing_cat.factorize()

### ISSUE THREAD

**Issue by Rockbaron** [ageron/handson-ml#104]
Dear Aurelien,

Might it be that the code in your latest jupyter implementation in chapter02,

    housing_cat.factorize()

does not work? I get the error "'DataFrame' object has no attribute 'factorize'"

I have found out that factorize cannot be applied to pandas df, but on pandas series. So the code should rather be used as

    pd.factorize(housing_cat["ocean_proximity"])

How do the follow up code has to be modified, in case this is right, to be continuous with the rest?

Thanks for your great book, code explanantion and very detailed jupyter notebooks. I love to read while in metro.

**Comment by ageron** [comment]
Hi @Rockbaron ,

Thanks for your feedback.  Sorry about that, I made a small change recently that I thought only made the code clearer, but it turns out it changed `housing_cat` from a `Series` to a single-column `DataFrame`, which crashed the following cell.  I just fixed this, you pull the latest code.
Thanks again!
