### ISSUE TITLE
Revised version of the book.

### ISSUE THREAD

**Issue by rvlander** [ageron/handson-ml#116]
I bought the first version of the book on Amazon via Kindle app. Is there a way to update to the last version? Especially is see that for the last chapter there were some important changes to the DQN training strategy.

**Comment by ageron** [comment]
Yes, it is possible to get the latest update:
* first option is to configure your kindle to automatically get the latest book updates: [how-to](https://www.amazon.com/gp/help/customer/display.html?nodeId=201252670).
* alternatively, you can manually update individual books:

1. Login to your Amazon account
2. Go to "Manage Your Content and Devices"
3. Check your list of purchased Kindle books
4. If any book has a newer version, you should see the "Update Available" button on the right hand side. Clicking on it will replace the original book with the newer version.

I have fixed a number of errors since the first edition came out.  Most of them are details, but indeed the DQN section in chapter 16 had a pretty serious error (my apologies): I fixed it a while ago so I think that the digital edition should now be up to date.  The printed edition was updated on Friday (November 3rd).

Hope this helps.

**Comment by rvlander** [comment]
@ageron, thanks for your answer.
I bought the book on May 6th. Apparently the book was already it's last version since there is no update option on the Amazon account.

The book is great, thanks a lot! Thanks to you I could catch up on these subjects and I can now read and understand papers such as the AlphaGo Zero (with a bit of work).

By the way, you wrote in your book that we had to put as much domain knowledge as possible in the models (reinforcement learning chapter), but it seems that AlphaGo Zero can learn better, faster, with less computational power than previous AlphaGo versions, and, above all from tabula rasa playing against itself, which is quite amazing.

**Comment by vd1** [comment]
@rvlander here is an interesting bunch of links on alpha go zero
https://www.reddit.com/r/reinforcementlearning/comments/778vbk/mastering_the_game_of_go_without_human_knowledge/
i totally agree alpha go zero is magical! no input (except for the rules)
and a few millions of play later, it is already superhuman.

**Comment by rvlander** [comment]
@vd1, thanks for the link
@ageron, I have the old version of the book (in the version I have, the Critic is trained, not the Actor). I can't see where I can update the book on my Amazon account: there is no button on the right hand side. Maybe you have to activate an option to make the changes available to those who already have bought the book like explained [here](https://kdp.amazon.com/en_US/help/topic/G200652370).

**Comment by ageron** [comment]
Hi @rvlander ,
Thanks for your feedback.  I actually work on my book through a git repo managed by O'Reilly, and they handle the actual releases.  They update the digital and paper editions on a regular basis, but perhaps my updates to chapter 16 were not released yet, I will check with them today, and I'll keep you posted.  In the meantime, you can follow along in the notebook, it is updated with the latest code.

**Comment by ageron** [comment]
Hi @rvlander ,
I just got an answer from O'Reilly: the latest update was sent to Amazon on Friday (November 3rd). They are not sure what the turnaround is for Amazon to make it available to customers, but hopefully just a day or two. They also told me that Amazon may not offer lifetime ebook updates. Do you see updates available for other any other ebook you have purchased through Amazon?

**Comment by rvlander** [comment]
Hi @ageron ,
this is the only book I bought on Amazon. The [link I gave you before](https://kdp.amazon.com/en_US/help/topic/G200652370) explains that by default new updates are not available to people who already have bought the book but that it can be turned on by the author. In your case I guess that O'Reilly can choose to turn this option on for your book.

**Comment by ageron** [comment]
Oops sorry, I missed your earlier link.  The link seems to be for direct publishing, i.e., authors directly publishing their ebooks, but perhaps O'Reilly has a similar option. I've just asked them, I'll let you know what they answer.  I have had readers tell me that they updated to the latest ebook version before, but I'm not sure they we talking about kindle version or safari version (or some other ebook version).

**Comment by rvlander** [comment]
The update have now been available for me (on Kindle) since the 9. Thanks.
And again, your book is great!

**Comment by ageron** [comment]
Hi @rvlander , thanks for letting me know.  O'Reilly told me that Amazon doesn't usually update books automatically (they say that it can lead to a poor user experience, in particular because of broken bookmarks, loosing highlighted sections, and so on).  However, if the changes are important enough, O'Reilly can ask for an update, and Amazon usually does it.  That's what happened last week.  I understand how updates work much better now: I make changes to my book almost every week (I push them to a git repo managed by O'Reilly), and I thought my changes were live in every digital version on the web within a couple weeks, but it turns out it's more complicated than that. People who purchase the book after my changes get the latest version, but people who bought it earlier on Amazon only get an update when O'Reilly asks for an update, and that's actually fairly rare.  Hope this helps.
