### ISSUE TITLE
Kernel crashes when launching DQN learning cell.

### ISSUE THREAD

**Issue by rvlander** [ageron/handson-ml#117]
I am trying to run the notebook for the last chapter notebook on my desktop. However, the kernel crashes when I try to run the cell for training the DQN for Pacman. Is anyone else having the issue?
Thanks.

**Comment by ageron** [comment]
Hi @rvlander ,
Thanks for your feedback. When the kernel crashes, it is generally due to an out-of-memory issue, a hardware problem, or some other low-level issue, not a problem in the actual notebook code.  You can try reducing the amount of memory required by the training code, for example by reducing the replay memory size.  If you are using a GPU (which is highly recommended when you are dealing with CNNs or RNNs), you should make sure that the GPU does not run out of memory.  This might mean reducing the batch size.  Also, make sure you don't have another tensorflow process running: it might have reserved all the GPU RAM for itself, leaving very little for your notebook.
I hope this helps.

**Comment by ageron** [comment]
If the problem persists, please provide more details about your platform (O.S., python version, tensorflow version, GPU type, amount of RAM, and so on).  Also, try to measure the amount of RAM and CPU usage while training.  How long into training does the kernel crash? What error do you get?
