### ISSUE TITLE
housing_cat_encoded.reshape(-1,1)

### ISSUE THREAD

**Issue by okdolly** [ageron/handson-ml#118]
>>> from sklearn.preprocessing import OneHotEncoder
>>> encoder = OneHotEncoder()
>>> housing_cat_1hot = encoder.fit_transform(housing_cat_encoded.reshape(-1,1)) >>> housing_cat_1hot
>>> housing_cat_1hot.toarray() array([[ 0., 1., 0., 0., 0.], [ 0., 1., 0., 0., 0.], [ 0., 0., 0., 0., 1.],
            ...,
            [ 0.,  1.,  0.,  0.,  0.],

Doesn't reshape(-1,1) mean that we have provided column as 1 but rows as unknown? Why would there be more than more columns?

**Comment by ageron** [comment]
Hi @okdolly,
Thanks for your question.  Indeed, `reshape(-1, 1)` will output a 2D array with a single column, and the appropriate number of rows (one per instance). We do this because the `OneHotEncoder` expects a 2D array, while `housing_cat_encoded` is a 1D array, so we need to reshape it.

A 1D array may look like this: [1., 2., 3., 4.] while a 2D array with a single column would look like this: [[1.], [2.], [3.], [4.]].

Does this answer your question?

**Comment by okdolly** [comment]
Yes!Sorry for the late reply.
