### ISSUE TITLE
Ms. Pacman DQN Memory Leak 

### ISSUE THREAD

**Issue by gkluber** [ageron/handson-ml#119]
I believe that there's a memory leak caused by the Ms. Pacman DQN code. I ran the code on my Windows 10 laptop and experienced an unbounded increase in RAM usage, which could not be attributed to the increasing size of the deque. It uses up all 6GB of free RAM. 
System specifications:
Windows 10 64-bit
NVIDIA GTX 1060 GPU
16GB RAM
Python version: WinPython 3.6

Note: I'm using https://github.com/j8lp/atari-py to program using the Ms. Pacman environment on Windows 10.

**Comment by ageron** [comment]
Hi @gkluber ,
The `replay_memory_size` is currently set to 500,000. When full, it takes up about 52 GB or RAM, which is way more than the 6 GB or RAM you have, so you should try reducing the memory size considerably (or install more RAM), for example down to 50,000 (try less first, just to see if this solves the out-of-memory issues).
Each element in the replay memory is a 5-tuple that contains an environment state, the chosen action, the resulting reward, the resulting state, and whether or not the game ended at that point. The largest pieces are the two environment states, which are represented as 88x80 pixel grayscale images. Each pixel takes up 8 bytes because it is represented as a 64-bit float (this is actually way more than needed, I will patch the `preprocess_observation()` function to cast the result to `float32` or `float16`, and that will reduce the memory footprint by 50% or 75%).
This means that each element in the replay memory takes up a bit over 2*88*80*8 = 112,640 bytes = 110kB. If the replay memory contains 500,000 elements, this adds up to about 52 GB of RAM.
Hope this helps.

**Comment by ageron** [comment]
Note: in general, I would recommend having a lot more RAM for Machine Learning, as many algorithms are much faster and better if they are given more RAM.  In particular, the larger the replay memory, the better, since this means that training instances within a training batch will be much less correlated.

**Comment by gkluber** [comment]
Oh, thanks! My error was that I failed to notice that the image is saved in the 5-tuple and thought that the parameter was just a floating-point number. 
Would you recommend modifying the DQN framework so that it operates as an out-of-core learning algorithm?

**Comment by ageron** [comment]
Actually, I thought a bit more about this: there's really no good reason to use 64-bit floats for pixel values.  As I mentioned above, you could replace them with 32 bit floats, or 16 bit floats, but in fact, the precision does not matter much in this case, so we can certainly use a single byte per pixel instead (I haven't tried it yet, but I believe it should work just fine).  Just replace the preprocessing function with this one should do the trick (In [57]):

```python
mspacman_color = 210 + 164 + 74

def preprocess_observation(obs):
    img = obs[1:176:2, ::2] # crop and downsize
    img = img.sum(axis=2) # to greyscale
    img[img==mspacman_color] = 0 # Improve contrast
    img = (img // 3 - 128).astype(np.int8) # normalize from -128 to 127
    return img.reshape(88, 80, 1)

img = preprocess_observation(obs)
```

The line that converts to greyscale returns a 2D array composed of 64-bit integers. Then the normalization line converts these 64-bit integers to signed bytes (from -128 to 127).

You may want to convert this array back to float32s in the `q_network()` function (In [59]), and scale the pixel values back to the -1.0 to 1.0 range, by replacing the first line of the function with this one:

```python
prev_layer = tf.cast(X_state, tf.float32) / 128.0
```

Using bytes instead of 64-bit floats should divide the RAM footprint by roughly 8, so instead of using 52 GB, it would just use 6.5 GB.  That's still a bit too much for your computer, but you can solve this by reducing the replay memory size slightly (e.g. down to 400,000).

Could you please tell me if this fixes your problem? I will probably update the notebook to reflect these changes within the next few days.

Hope this helps.
