### ISSUE TITLE
Chapter11: Graph vs default_graph

### ISSUE THREAD

**Issue by ChrisQlasty** [ageron/handson-ml#123]
Hello @ageron , chapter 11 of your great book is one of the most interesting to me.
I have adopted your clean solution of Exercise 8.3 to my needs and it seems to be working properly.
However, there are some details I am not sure about. I couldn't make the customized RandomizedSearchCV  working without these subtle changes:

1. in the `fit()` method, just after `self.close_session()` I added a line `tf.reset_default_graph()`
2. also in the `fit()` method, instead of `self._graph = tf.Graph()` I just typed `self._graph = tf.get_default_graph()`

Without these changes, depending on the combination of inserted lines, I get one of the following errors:
- Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph - [this happens just after training on the first fold has completed but it cannot be evaluated on the validation set]
- Variable rnn/multi_rnn_cell/cell_0/gru_cell/gates/kernel already exists, disallowed - [this happens after validating the first fold]

Is there any practical reason that your solution looks just like this or these solutions can be considered as equal in terms of effect and I just possibly messed something with the code? Or is the solution with resetting a graph more general; immune to placing part of the code associated with the build-graph phase outside of a proper method (but maybe for some reason not recommended though)?

And I just want to add that I am still surprised how practical I find your book by getting deeper into ML and implementation of the models. Thank you for your efforts!

**Comment by ageron** [comment]
Hi @ChrisQlasty ,
Thanks for your question and your kind words regarding my book. I'm glad you find it useful.

TensorFlow lets you create as many different graphs as you want, but only one of them is TensorFlow's default graph.  In my `DNNClassifier` class, I chose to create a dedicated graph for each classifier instance: this makes it possible to have several `DNNClassifier` instances, each using different hyperparameters (e.g., different number of neurons or hidden layers), because each instance will have its own graph, without collisions. If you use the default graph instead, then all `DNNClassifier` instances will share the same graph, which is definitely not what you want.

Now when you want to evaluate a tensor in TensorFlow, you need to create a session and tell it what graph it should use. So in `DNNClassifier`, I also have a dedicated session, built to use the dedicated graph. However, I just noticed that the class uses the function `tf.get_collection()` (twice). This is an error: indeed, this is a wrapper for `tf.get_default_graph().get_collection()`! So we are actually using the default graph for collections. I will replace this with: `self._graph.get_collection()`, and everything should work fine. It's unclear to me why my notebook didn't get the same error as you. I'll investigate this.

I hope this fixes your problem, thanks for catching this error.

Cheers,
Aurélien

**Comment by ChrisQlasty** [comment]
Thank you for your explanation @ageron .

Ok, so as I understand it, when we take variable rnd_search which is a type of RandomizedSearchCV and call it's method .fit() a number (cv * n_iter) of different graphs is created in your solution. So apart of the .fit() method probably some other methods are called under the hood (which for example fill the .cv_results_ ). But if (if?) all of the ops related with evaluating the performance of a model of topology based on the set of sampled hyperparams can be completed within a single run of .fit() (and some possible helper methods) would we need such graph for the future? 

Anyway, I have performed a test, which reflects what I mean by "seems to be working properly" from my first post:
`param_distribs = {
        "n_neurons": [20],
        "learning_rate": [0.01,0.001,0.0001],      
        "n_hidden_layers": [1]
    }`
`rnd_search = RandomizedSearchCV(
RNNclassifier(random_state=42),
                param_distribs,
                n_iter=3,
                random_state=42,
                verbose=2,
                cv=2,
                return_train_score=True)`
  `myFD = {"I_valid": I_val,   "L_valid": L_val,   "T_valid": T_val,
            "I_train": I_train, "L_train": L_train, "T_train": T_train,
            "n_epochs": 1}`
`rnd_search.fit(I_train, T_train, **myFD)`

And the output was as follows:

>Fitting 2 folds for each of 3 candidates, totalling 6 fits
>
>[CV] learning_rate=0.01, n_neurons=20, n_hidden_layers=1 .............
>5	Validation loss: 1.2798	Best acc: 55.210%	Accuracy: 55.210%
>10	Validation loss: 0.8947	Best acc: 69.358%	Accuracy: 69.358%
>15	Validation loss: 0.6579	Best acc: 78.173%	Accuracy: 78.173%
>20	Validation loss: 0.5587	Best acc: 81.457%	Accuracy: 81.457%
>[CV]  learning_rate=0.01, n_neurons=20, n_hidden_layers=1, total= 3.9min
>[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.9min remaining:    0.0s
>[CV] learning_rate=0.01, n_neurons=20, n_hidden_layers=1 .............
>5	Validation loss: 1.3894	Best acc: 49.926%	Accuracy: 49.926%
>10	Validation loss: 0.9700	Best acc: 67.062%	Accuracy: 67.062%
>15	Validation loss: 0.7916	Best acc: 72.025%	Accuracy: 72.025%
>20	Validation loss: 0.6304	Best acc: 80.272%	Accuracy: 80.272%
>[CV]  learning_rate=0.01, n_neurons=20, n_hidden_layers=1, total= 4.0min
>
>[CV] learning_rate=0.001, n_neurons=20, n_hidden_layers=1 ............
>5	Validation loss: 2.4928	Best acc: 22.123%	Accuracy: 22.123%
>10	Validation loss: 1.9749	Best acc: 32.568%	Accuracy: 32.568%
>15	Validation loss: 1.8049	Best acc: 36.247%	Accuracy: 36.247%
>20	Validation loss: 2.3687	Best acc: 36.247%	Accuracy: 23.580%
>[CV]  learning_rate=0.001, n_neurons=20, n_hidden_layers=1, total= 3.8min
>[CV] learning_rate=0.001, n_neurons=20, n_hidden_layers=1 ............
>5	Validation loss: 2.5539	Best acc: 18.370%	Accuracy: 18.370%
>10	Validation loss: 2.0145	Best acc: 31.556%	Accuracy: 31.556%
>15	Validation loss: 1.7492	Best acc: 36.963%	Accuracy: 36.963%
>20	Validation loss: 1.6305	Best acc: 40.346%	Accuracy: 40.346%
>[CV]  learning_rate=0.001, n_neurons=20, n_hidden_layers=1, total= 4.0min
>
>[CV] learning_rate=0.0001, n_neurons=20, n_hidden_layers=1 ...........
>5	Validation loss: 3.2775	Best acc: 8.716%	Accuracy: 8.716%
>10	Validation loss: 3.2121	Best acc: 14.099%	Accuracy: 14.099%
>15	Validation loss: 3.1016	Best acc: 16.099%	Accuracy: 16.099%
>20	Validation loss: 2.9567	Best acc: 16.099%	Accuracy: 13.704%
>[CV]  learning_rate=0.0001, n_neurons=20, n_hidden_layers=1, total= 4.3min
>[CV] learning_rate=0.0001, n_neurons=20, n_hidden_layers=1 ...........
>5	Validation loss: 3.2777	Best acc: 8.568%	Accuracy: 8.568%
>10	Validation loss: 3.2113	Best acc: 13.531%	Accuracy: 13.531%
>15	Validation loss: 3.0991	Best acc: 17.432%	Accuracy: 17.432%
>20	Validation loss: 2.9666	Best acc: 17.432%	Accuracy: 14.543%
>[CV]  learning_rate=0.0001, n_neurons=20, n_hidden_layers=1, total= 4.3min
>
>[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed: 24.7min finished
>5	Validation loss: 0.9204	Best acc: 68.741%	Accuracy: 68.741%
>10	Validation loss: 0.6132	Best acc: 79.383%	Accuracy: 79.383%
>15	Validation loss: 0.5016	Best acc: 84.272%	Accuracy: 84.272%
>20	Validation loss: 0.3808	Best acc: 88.049%	Accuracy: 88.049%

 `print(rnd_search.best_params_)`
>{'learning_rate': 0.01, 'n_neurons': 20, 'n_hidden_layers': 1}

 `cvres = rnd_search.cv_results_ `
  `for mean_score, params in zip(cvres["mean_test_score"], cvres["params"]): `
 ` print(mean_score, params) `
>0.810899470899 {'learning_rate': 0.01, 'n_neurons': 20, 'n_hidden_layers': 1}
>0.377566137566 {'learning_rate': 0.001, 'n_neurons': 20, 'n_hidden_layers': 1}
>0.168042328042 {'learning_rate': 0.0001, 'n_neurons': 20, 'n_hidden_layers': 1}

 `print(accuracy_score(T_test, T_pred)) `
>0.876049382716

So it looks that every time model takes new set of hyperparams, is being trained from scratch, saves the values to cv_results_ so it does what I would expect.

And just to answer your question:
- the error about the default session is raised from  `def predict_proba(self, X):` where first `.eval()` is called (I do one op on the X before the `return` statement).
- the error about graphs is raised from `_build_graph()` method at the line where `tf.nn.dynamic_rnn` is used

Does this look any kind of reliable in your opinion or there are some facts I did not take into account?
Best regards.

**Comment by ageron** [comment]
> But if (if?) all of the ops related with evaluating the performance of a model of topology based on the set of sampled hyperparams can be completed within a single run of .fit() (and some possible helper methods) would we need such graph for the future?

If you only use one instance of the `DNNClassifier` class at a time, then yes it should work fine, but I think it's a bit risky in the long run because at one point someone may create two instances and they won't expect them to be tied (imagine having an `Account`class, creating one instance with $100, then another with $5, and suddenly you notice that the first instance now has $5: quite unexpected, each instance should be independent). I think it's preferable to try to find where the bug is in the initial implementation (the one with one graph per `DNNClassifier` instance).

I cannot seem to reproduce the issue you are getting.  Could you please send me a code sample that produces the error? Thanks.

**Comment by ChrisQlasty** [comment]
Thank you for this example and pointing out which solution is more safe. I will take a moment and clean my scripts a bit before sending. Thank you for your help.

**Comment by ageron** [comment]
Hi @ChrisQlasty ,

I received your code and I think I found the problem. Here is what your `predict_proba()` method looks like:

```python
def predict_proba(self, X):
    if not self._session:
        raise NotFittedError(
            "This %s instance is not fitted yet" % self.__class__.__name__)
    with self._session.as_default() as sess:
        # Danijar - https://danijar.com/variable-sequence-lengths-in-tensorflow/
        used = tf.sign(tf.reduce_max(tf.abs(X), 2))
        length = tf.reduce_sum(used, 1)
        length = tf.cast(length, tf.int32)
        seq_length = length.eval() #lengths of sequences

        return self._Y_proba.eval(feed_dict={self._X: X, self._seq_length: seq_length})
```

The problem is that the `length` tensor is actually created in TensorFlow's default graph, *not* in the session's graph. So when you try to evaluate it using `self._session`, it will complain that the tensor was not defined in the session's graph.  Here's a simple example that reproduces the issue:

```python
import tensorflow as tf

g = tf.Graph()
with g.as_default():
  x = tf.constant(1.0)  # x is created in graph g

s = tf.Session(graph=g)
with s.as_default() as sess:
  print(x.eval()) # x was created in graph g and it is evaluated in session s
                  # which is tied to graph g, so everything is ok.
  y = tf.constant(2.0) # y is created in TensorFlow's default graph!!!
  print(b.eval()) # y was created in TF's default graph, but it is evaluated in
                  # session s which is tied to graph g => ERROR
```

The best fix is to cleanly separate the construction phase and the execution phase (in your code, they are mixed). In my simple example, this is what it would look like:

```python
import tensorflow as tf

g = tf.Graph()
with g.as_default():
  x = tf.constant(1.0)  # x is created in graph g
  y = tf.constant(2.0) # y is created in graph g

s = tf.Session(graph=g)
with s.as_default() as sess:
  print(x.eval()) # x was created in graph g and it is evaluated in session s
                         # which is tied to graph g, so everything is ok.
  print(y.eval()) # y was created in graph g and it is evaluated in session s
                         # which is tied to graph g, so everything is ok.
```

In your code, try moving the definition of `used` and `length` to the `_build_graph()` method.

In general, be careful not to create TF operations after the construction phase: it can not only the cause problems you got, but you may also end up adding more and more nodes to your graph.

Hope this helps,
Aurélien

**Comment by ChrisQlasty** [comment]
Hi @ageron , that was the point.
My understanding of sessions and graphs is definitely better right now - thank you for this nice example! It turned out that it was not necessary to have those lines in `predict_proba` to make it working so indeed I moved them to the method where the graph was constructed. Now the script executes each instance in it's own graph, which is a preferred solution as you explained earlier.
So thank you again for your time, next tips and suggestions.

Krzysztof

--
Btw, please fix a tiny typo (should be `print(y.eval()` in the second code block of your last answer).

**Comment by ageron** [comment]
Hi @ChrisQlasty ,
Great! Thanks for your feedback, I'm really glad this solved your problem. I also fixed the typo, thanks.
Cheers, Aurélien

**Comment by futuramark** [comment]
Hello I am also having this  issue..ValueError: Cannot use the default session to execute operation: the operation's graph is different from the session's graph. Pass an explicit session to run(session=sess).
was also having some trouble with tensorflow-estimator i reinstalled 

I am unable to trian model and do autoencoders at this point.
