### ISSUE TITLE
chapter 2: What is the correct way of creating a pipeline

### ISSUE THREAD

**Issue by akjain90** [ageron/handson-ml#154]
I really appreciate your work and the efforts that you took by creating this whole series of notebooks.
My issue is regarding the transformation pipeline which you are creating in cell 73 as follows:

```python
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

num_pipeline = Pipeline([
        ('selector', DataFrameSelector(num_attribs)),
        ('imputer', Imputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

cat_pipeline = Pipeline([
        ('selector', DataFrameSelector(cat_attribs)),
        ('cat_encoder', CategoricalEncoder(encoding="onehot-dense")),
    ])
```

The first component of the numerical pipeline is `DataframeSelector` which returns a dataframe without a categorical entry ie `ocean_proximity`.  Further operations are `Imputer` and `CombinedAttributesAdder`.

Just before the definition of `CombinedAttributesAdder` class in cell 68, you define the column index that needs to be combined, as follows:

```python
rooms_ix, bedrooms_ix, population_ix, household_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self  # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]
```

In the present case `ocean_proximity` is the last column and that's why our column index doesn't change even after calling the `DataframeSelector`. But in case `ocean_proximity` is not the last feature we need to calculate the updated column index before hand which could be very tedious work in case we have a huge set of features. 

So what I wanted to ask (This could be a silly doubt ) is, is there a standard way of doing the above-mentioned procedure?

Thank you.

**Comment by ageron** [comment]
Hi @akjain90 ,
Thanks for your kind words and for your question. Unfortunately, Scikit-Learn is not integrated with Pandas. Sure, you can feed any Scikit-Learn transformer a DataFrame as input, but it will output a NumPy array, so you lose the index and column information.
In [Pull Request #9012](https://github.com/scikit-learn/scikit-learn/pull/9012), there's a `ColumnTransformer` class that could help, so if it is merged one day, things will be simpler, since it will be easy to do different transformations for each column.  In the meantime, you can copy it in your code if you find it useful.
Another option is to run `pip3 install sklearn-pandas` to get a `DataFrameMapper` class with a similar objective.
I guess another option would be to create a `DataframeTransformer` class that could wrap any regular Scikit-Learn transformer, and it would add the index and column names to the output of the transformation. Similarly, one could create a `DataFramePredictor` class that would wrap any predictor, and would output a `DataFrame` (or `Series`) with the appropriate index and columns.
Hope this helps,
Aurélien

**Comment by akjain90** [comment]
Thank you for the inputs. Will check all these possibilities.

**Comment by YiRongZhuang** [comment]
CategoricalEncoder briefly existed in 0.20dev. Its functionality has been rolled into the OneHotEncoder and OrdinalEncoder. This stub will be removed in version 0.21.

**Comment by VicktorKrum** [comment]
Hi,
Can you kindly explain how to use CombinedAttributesAdder() directly from library? I have done the code from the book where it is first used and am getting 
"AttributeError: 'DataFrame' object has no attribute 'dtype' " error. 
Kindly help me with how to fix it. 
Thank You.

**Comment by PrasadGadekar101** [comment]
> 
> 
> Hi,
> Can you kindly explain how to use CombinedAttributesAdder() directly from library? I have done the code from the book where it is first used and am getting error that it is not defined.
> 
> Kindly help me with how to fix it.
> Thank You.

Need to create the CombinedAttributesAdder() class which comes under the custom transformer section of the code...

**Comment by Phanttan** [comment]
Thank you @ageron , I am using **DataFrameMapper** in _sklearn_pandas_ and it is so useful.
