### ISSUE TITLE
CategoricalEncoder

### ISSUE THREAD

**Issue by magicmutal** [ageron/handson-ml#155]
Hi, my name is Jinsu. I really enjoy your book!!
I am writing to get some help
The problem is that I cannot import "CategoricalEncoder"

this is the code on the book
----------------------------------------------------------------------------
>>> from sklearn.preprocessing import CategoricalEncoder
>>> cat_encoder = CategoricalEncoder()
>>> housing_cat_reshaped = housing_cat.values.reshape(-1, 1)
>>> housing_cat_1hot = cat_encoder.fit_trasform(housing_cat_reshaped)
>>> housing_cat_1hot
-------------------------------------------------------------------------

this is the message 
----------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-52-d3b4254edae8> in <module>()
      1 #Transformation text to integer and integer to one-hot vector
----> 2 from sklearn.preprocessing import CategoricalEncoder
      3 cat_encoder = CategoricalEncoder()
      4 housing_cat_reshaped = housing_cat.values.reshape(-1, 1)
      5 housing_cat_1hot = cat_encoder.fit_trasform(housing_cat_reshaped)

ImportError: cannot import name 'CategoricalEncoder'
-----------------------------------------------------------------------------------

What do I need to do????

**Comment by ageron** [comment]
Hi @magicmutal ,
Thanks for your kind words, I'm really glad you enjoy the book! :)
The `CategoricalEncoder` class is only available since Scikit-Learn 0.20 (currently the dev version).  So you should either update Scikit-Learn to the dev version, or simply copy the definition of the class in a `categorical_encoder.py` file in your code base, and just import that one until you can update to Scikit-Learn 0.20.  The source code is [here](https://github.com/scikit-learn/scikit-learn/blob/34155a2/sklearn/preprocessing/data.py#L2869), it's pretty standalone, so you can mostly copy it and add the relevant imports, or just copy the code in cell #63 in the [Jupyter notebook for chapter 2](https://github.com/ageron/handson-ml/blob/master/02_end_to_end_machine_learning_project.ipynb).
I hope this helps,
Aurélien

**Comment by swzCuroverse** [comment]
Hello,

I am interested in using the current version of Categorical Encoder for memory concerns.  I have install the dev version (0.20.dev0), should I just use Categorical Encoder or is the functionality already rolled up into OneHotEncoder.  I get the following message:

  File "<stdin>", line 1, in <module>
  File "/scikit-learn/sklearn/preprocessing/data.py", line 2839, in __init__
    "CategoricalEncoder briefly existed in 0.20dev. Its functionality "
RuntimeError: CategoricalEncoder briefly existed in 0.20dev. Its functionality has been rolled into the OneHotEncoder and OrdinalEncoder. This stub will be removed in version 0.21.

Cheers,
Sarah

**Comment by ageron** [comment]
Hi @swzCuroverse ,

Thanks for your question. You should use the new `sklearn.preprocessing.OneHotEncoder` class from sklearn 0.20 (not the one from 0.19).  I updated the notebook for chapter 2 to explain this.

Hope this helps,
Aurélien

**Comment by VirajVaitha123** [comment]
Hi Ageron,

I have just started using your book and I am learning a lot thank you!

For the California House Prices Project, must you use OrdinalEncoder followed by the OneHotEncoder. 

I am unable to import OrdinalEncorder from SkLearn Pre Processing or Future Encorders. The error I receive afterwards when only using One Hot Encoding is ValueError: could not convert string to float: 'NEAR BAY'.


Thanks and sorry If the question is great,
Viraj

**Comment by ageron** [comment]
Hi @VirajVaitha123 ,

Did you resolve this issue? If not, can you please specify which versions you are using for your OS, Python, and Scikit-Learn?

**Comment by morphley** [comment]
@ageron  I have the same issue as @VirajVaitha123 

_**HANDLING TEXT AND CATEGORICAL ATTRIBUTES**_
everything works fine till **cell 60**.  What problem we are trying to solve ? The categorical attribute _ocean_proximity_ is a text attribute --> So we cannot compute its median. In general ML algorithms like to work with numbers. So we try to convert the text labels _ocean_proximity_ to numbers. We use the OneHotEncoder to convert integer categorical values into one-hot encoding ( because the ML algorithm that two nearby values are more similar than two distant values).  

**INPUT:**

`try:
    from sklearn.preprocessing import OrdinalEncoder
except ImportError:
    from future_encoders import OrdinalEncoder # Scikit-Learn < 0.20`


**OUTPUT:**

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-66-db6cd26b8e60> in <module>()
      1 try:
----> 2     from sklearn.preprocessing import OrdinalEncoder
      3 except ImportError:

ImportError: cannot import name 'OrdinalEncoder' from 'sklearn.preprocessing' (/Users/morphley/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/__init__.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-66-db6cd26b8e60> in <module>()
      2     from sklearn.preprocessing import OrdinalEncoder
      3 except ImportError:
----> 4     from future_encoders import OrdinalEncoder # Scikit-Learn < 0.20

ModuleNotFoundError: No module named 'future_encoders'
`

I checked the source code of [scikit-learn/sklearn/preprocessing/data.py](https://github.com/scikit-learn/scikit-learn/blob/34155a2/sklearn/preprocessing/data.py#L2869) and there is no definition of an OrdinalEncoder. Even when I tried to only insert following:

`
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot` 

I received this error message:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-60-9711bf090fc7> in <module>()
      2 
      3 cat_encoder = OneHotEncoder()
----> 4 housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
      5 housing_cat_1hot

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py in fit_transform(self, X, y)
   2017         """
   2018         return _transform_selected(X, self._fit_transform,
-> 2019                                    self.categorical_features, copy=True)
   2020 
   2021     def _transform(self, X):

~/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py in _transform_selected(X, transform, selected, copy)
   1807     X : array or sparse matrix, shape=(n_samples, n_features_new)
   1808     """
-> 1809     X = check_array(X, accept_sparse='csc', copy=copy, dtype=FLOAT_DTYPES)
   1810 
   1811     if isinstance(selected, six.string_types) and selected == "all":

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    431                                       force_all_finite)
    432     else:
--> 433         array = np.array(array, dtype=dtype, order=order, copy=copy)
    434 
    435         if ensure_2d:

ValueError: could not convert string to float: 'NEAR BAY'`



Information about my system:
Im using a Macbook 2,4 GHz Intel Core i7


Morphleys-MacBook-Pro:~ morphley$ conda list
# packages in environment at /Users/morphley/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.11                   py37_0  
anaconda                  5.3.1                    py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.2                    py37_0  
anaconda-project          0.8.2                    py37_0  
appdirs                   1.4.3            py37h28b3542_0  
appnope                   0.1.0                    py37_0  
appscript                 1.0.1            py37h1de35cc_1  
asn1crypto                0.24.0                   py37_0  
astroid                   2.0.4                    py37_0  
astropy                   3.0.4            py37h1de35cc_0  
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
automat                   0.7.0                    py37_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.6.3                    py37_0  
bitarray                  0.8.3            py37h1de35cc_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py37_0  
bleach                    2.1.4                    py37_0  
blosc                     1.14.4               hd9629dc_0  
bokeh                     0.13.0                   py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h1d22016_1  
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37h6174b99_1  
chardet                   3.0.4                    py37_1  
click                     6.7                      py37_0  
cloudpickle               0.5.5                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.3.9                    py37_0  
conda                     4.5.12                   py37_0  
conda-build               3.15.1                   py37_0  
conda-env                 2.6.0                         1  
constantly                15.1.0           py37h28b3542_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.4.2            py37ha12b0ac_0  
curl                      7.63.0            ha441bb4_1000  
cycler                    0.10.0                   py37_0  
cython                    0.28.5           py37h0a44026_0  
cytoolz                   0.9.0.1          py37h1de35cc_1  
dask                      0.19.1                   py37_0  
dask-core                 0.19.1                   py37_0  
datashape                 0.5.4                    py37_1  
dbus                      1.13.2               h760590f_1  
decorator                 4.3.0                    py37_0  
defusedxml                0.5.0                    py37_1  
distributed               1.23.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.2.3                    py37_2  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
fastcache                 1.0.2            py37h1de35cc_2  
filelock                  3.0.8                    py37_0  
flask                     1.0.2                    py37_1  
flask-cors                3.0.6                    py37_0  
freetype                  2.9.1                hb4e5f40_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.3.6            py37h1de35cc_0  
glib                      2.56.2               hd9629dc_0  
glob2                     0.6                      py37_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py37h6ef4df4_2  
greenlet                  0.4.15           py37h1de35cc_0  
h5py                      2.8.0            py37h878fce3_3  
hdf5                      1.10.2               hfa1e0ec_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
hyperlink                 18.0.0                   py37_0  
icu                       58.2                 h4b95b61_1  
idna                      2.7                      py37_0  
imageio                   2.4.1                    py37_0  
imagesize                 1.1.0                    py37_0  
incremental               17.5.0                   py37_0  
intel-openmp              2019.0                      118  
ipykernel                 4.9.0                    py37_1  
ipython                   6.5.0                    py37_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.1                    py37_0  
isort                     4.3.4                    py37_0  
itsdangerous              0.24                     py37_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.4                      py37_0  
jedi                      0.12.1                   py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.3                    py37_0  
jupyter_console           5.2.0                    py37_1  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.34.9                   py37_0  
jupyterlab_launcher       0.13.1                   py37_0  
keyring                   13.2.1                   py37_0  
kiwisolver                1.0.1            py37h0a44026_0  
krb5                      1.16.1               hddcf347_7  
lazy-object-proxy         1.3.1            py37h1de35cc_2  
libcurl                   7.63.0            h051b688_1000  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.16               h3efe00b_0  
libssh2                   1.8.0                ha12b0ac_4  
libtiff                   4.0.9                hcb84e12_2  
libxml2                   2.9.8                hab757c2_1  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.24.0           py37hc454e04_0  
locket                    0.2.0                    py37_1  
lxml                      4.2.5            py37hef8c89e_0  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py37h1de35cc_1  
matplotlib                2.2.3            py37h54f8f79_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.3            py37h1de35cc_1  
mkl                       2019.0                      118  
mkl-service               1.1.2            py37h6b9c3cc_5  
mkl_fft                   1.0.4            py37h5d10147_1  
mkl_random                1.0.1            py37h5d10147_1  
more-itertools            4.3.0                    py37_0  
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.0.0                    py37_2  
msgpack-python            0.5.6            py37h04f5b5a_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.0                    py37_1  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_0  
networkx                  2.1                      py37_0  
nltk                      3.3.0                    py37_0  
nose                      1.3.7                    py37_2  
notebook                  5.6.0                    py37_0  
numba                     0.39.0           py37h6440ff4_0  
numexpr                   2.6.8            py37h1dc9127_0  
numpy                     1.15.1           py37h6a91979_0  
numpy-base                1.15.1           py37h8a80b8c_0  
numpydoc                  0.8.0                    py37_0  
odo                       0.5.1                    py37_0  
olefile                   0.46                     py37_0  
openpyxl                  2.5.6                    py37_0  
openssl                   1.1.1a               h1de35cc_0  
packaging                 17.1                     py37_0  
pandas                    0.23.4           py37h6440ff4_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2                    py37_1  
parso                     0.3.1                    py37_0  
partd                     0.3.8                    py37_0  
path.py                   11.1.0                   py37_0  
pathlib2                  2.3.2                    py37_0  
patsy                     0.5.0                    py37_0  
pcre                      8.42                 h378b8a2_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.4                    py37_0  
pillow                    5.2.0            py37hb68e598_0  
pip                       10.0.1                   py37_0  
pkginfo                   1.4.2                    py37_1  
pluggy                    0.7.1            py37h28b3542_0  
ply                       3.11                     py37_0  
prometheus_client         0.3.1            py37h28b3542_0  
prompt_toolkit            1.0.15                   py37_0  
psutil                    5.4.7            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.6.0                    py37_0  
pyasn1                    0.4.4            py37h28b3542_0  
pyasn1-modules            0.2.2                    py37_0  
pycodestyle               2.4.0                    py37_0  
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.18                     py37_1  
pycrypto                  2.6.1            py37h1de35cc_9  
pycurl                    7.43.0.2         py37ha12b0ac_0  
pyflakes                  2.0.0                    py37_0  
pygments                  2.2.0                    py37_0  
pylint                    2.1.1                    py37_0  
pyodbc                    4.0.24           py37h0a44026_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.2.0                    py37_1  
pyqt                      5.9.2            py37h655552a_2  
pysocks                   1.6.8                    py37_0  
pytables                  3.4.4            py37h13cba08_0  
pytest                    3.8.0                    py37_0  
pytest-arraydiff          0.2              py37h39e3cac_0  
pytest-astropy            0.4.0                    py37_0  
pytest-doctestplus        0.1.3                    py37_0  
pytest-openfiles          0.3.0                    py37_0  
pytest-remotedata         0.3.0                    py37_0  
python                    3.7.1                haf84260_7  
python-dateutil           2.7.3                    py37_0  
python.app                2                        py37_8  
pytz                      2018.5                   py37_0  
pywavelets                1.0.0            py37h1d22016_0  
pyyaml                    3.13             py37h1de35cc_0  
pyzmq                     17.1.2           py37h1de35cc_0  
qt                        5.9.6                h45cd832_2  
qtawesome                 0.4.4                    py37_0  
qtconsole                 4.4.1                    py37_0  
qtpy                      1.5.0                    py37_0  
readline                  7.0                  h1de35cc_5  
requests                  2.19.1                   py37_0  
rope                      0.11.0                   py37_0  
ruamel_yaml               0.15.46          py37h1de35cc_0  
scikit-image              0.14.0           py37h0a44026_1  
scikit-learn              0.19.2           py37h4f467ca_0  
scipy                     1.1.0            py37h28f7352_1  
seaborn                   0.9.0                    py37_0  
send2trash                1.5.0                    py37_0  
service_identity          17.0.0           py37h28b3542_0  
setuptools                40.2.0                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.11.0                   py37_1  
snappy                    1.1.7                he62c110_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.0.1                    py37_0  
sortedcontainers          2.0.5                    py37_0  
sphinx                    1.7.9                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.1                    py37_1  
spyder-kernels            0.2.6                    py37_0  
sqlalchemy                1.2.11           py37h1de35cc_0  
sqlite                    3.26.0               ha441bb4_0  
statsmodels               0.9.0            py37h1d22016_0  
sympy                     1.2                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.3.1                    py37_0  
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1              py37h1de35cc_0  
tqdm                      4.26.0           py37h28b3542_0  
traitlets                 4.3.2                    py37_0  
twisted                   18.7.0           py37h1de35cc_1  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.23                     py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.31.1                   py37_0  
widgetsnbextension        3.4.1                    py37_0  
wrapt                     1.10.11          py37h1de35cc_2  
xlrd                      1.1.0                    py37_1  
xlsxwriter                1.1.0                    py37_0  
xlwings                   0.11.8                   py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zict                      0.1.3                    py37_0  
zlib                      1.2.11               hf3cbc9b_2  
zope                      1.0                      py37_1  
zope.interface            4.5.0            py37h1de35cc_0  
Morphleys-MacBook-Pro:~ morphley$

**Comment by morphley** [comment]
@ageron  Solved the issue..

**Comment by morphley** [comment]
@ageron  First of all great book. I have a couple of questions regarding chapter 2  **End-to-End Machine Learning Projects**  The documentation about Pipelines on scikilearn.org is very complicated ... 

We created a train_set (strat_train_set)  and a test_set (strat_test_set) using stratified sampling. In the next step before feeding our ML algorithms we need to cleanup and prepare the data. We can do this automatically by using Pipelines. We use a Pipeline to execute transformation steps on our data in the right order. 

First Pipeline (only for numerical values):
```
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])
```
**Question:  What kind of Transformer is the StandardScaler() ? **  


When you call the pipeline _fit()_ method it call _fit_transform()_ sequentially on all transformers passing the output of each call as the parameter to the next call until it reaches the final estimator for which it just calls the _fit()_ method 


`housing_num_tr = num_pipeline.fit_transform(housing_num)`


But we need a full pipeline which can handle both numerical and categorical attributes: 

```
try:
    from sklearn.compose import ColumnTransformer
except ImportError:
    from future_encoders import ColumnTransformer # Scikit-Learn < 0.20

num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing)
```
**Question: Can you please explain how the ColumnTransformer works and how it knows how to put the table together.**

**Question: You mention cleaning and preparing the data. What kind of data transformation possibilities  exists such as  replace missing values, combine features etc.**

**Comment by ageron** [comment]
Hi @morphley ,
Great questions. I'm traveling this week, but I'll try to answer next week.

**Comment by subhap15** [comment]
> @ageron Solved the issue..



> @ageron Solved the issue..

@morphley I am getting the same error ("ModuleNotFoundError: No module named 'future_encoders'. and "ValueError: could not convert string to float: '<1H OCEAN'"). Do you mind sharing how you solved this issue? TIA!

**Comment by ageron** [comment]
Hi @subhap15 , make sure you have the `future_encoders.py` file (located at the root of this project) in the same directory as the notebook.
Happy new year!

**Comment by subhap15** [comment]
Hi @ageron , That worked. Thank you so much for the reply! Your book is truly awesome! Happy New Year to you too!

**Comment by morphley** [comment]
@subhap15 make sure that you install the latest release of sklearn

pip
pip install -U scikit-learn
or conda:
conda install scikit-learn

**Comment by subhap15** [comment]
@morphley  I will do that as well. Thank you

**Comment by morphley** [comment]
@suhap15  You welcome  . You can contact me anytime . Cheers

**Comment by ibozkurt79** [comment]
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing)


At the code line above , we are trying to fit categorical data without labelencoding first and it gave me error when I try the pipeline. I think somewhere before the pipeline we need to convert the categorical column with Labeleencoder. I did try but my kernel died. Here is my trial


num_attribs = list(housing_num)
#cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), housing_cat_encoded),
    ])

housing_prepared = full_pipeline.fit_transform(housing)

**Comment by SerenityHow** [comment]
I just started reading and working through the book and really enjoyed it.  Thanks!  I upgraded sklearn to 0.20.2. and it appears that CategoricalEncoder is now implemented through OneHotEncoder.  I used the following and it seems to work.

num_pipeline = Pipeline([
                        ('selector',DataFrameSelector(num_attribs)),
                        ('imputer', SimpleImputer(strategy='median')),
                        ('attrib_adder', HousingCombinedAttributesAdder()),
                        ('std_scaler', StandardScaler())
                        ])

cat_pipeline = Pipeline([
                        ('selector', DataFrameSelector(cat_attribs)),
                        ('encoder', OneHotEncoder(categories='auto',sparse=False))
                        ])

full_pipeline = FeatureUnion(transformer_list=[
                            ('num_pipeline',num_pipeline),
                            ('cat_pipeline',cat_pipeline)
                            ])

**Comment by ayushs2k1** [comment]
Hi @ageron, I'm loving this book! I'm new to ML and would love some guidance here. 

I had a doubt which I wanted to clarify.

The code written in the book for making the full pipeline goes like this:

```
num_attribs = list(housing_num)
cat_attribs = ["ocean_proximity"]

old_num_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(num_attribs)),
        ('imputer', SimpleImputer(strategy="median")),
        ('attribs_adder', CombinedAttributesAdder()),
        ('std_scaler', StandardScaler()),
    ])

old_cat_pipeline = Pipeline([
        ('selector', OldDataFrameSelector(cat_attribs)),
        ('cat_encoder', OneHotEncoder(sparse=False)),
    ])
```

And here goes my code(though not much of a difference):

```
from sklearn.compose import ColumnTransformer
num_attribs=list(housing_num)
cat_attribs=list(housing_cat)

full_pipeline=ColumnTransformer([
        ("num",num_pipeline,num_attribs),
        ("cat",OneHotEncoder(),cat_attribs),
    ])
housing_prepared=full_pipeline.fit_transform(housing)
```
 
Notice how I changed the cat_attribs that was written originally. I wanted to know if that makes any difference to the code or is it the same thing. If it does make a difference, how?

According to my understanding of this chapter, it shouldn't. Also, the shape of housing_prepared that I'm getting is same.

**Comment by ageron** [comment]
Hi @jinsu-kim ,
`list(housing_cat)` is equal to `["ocean_proximity"]`, to it's exactly the same thing. 👍 
Hope this helps
