### ISSUE TITLE
gradient equals 0 in python 2

### ISSUE THREAD

**Issue by Emilio66** [ageron/handson-ml#16]
Hi, ageron, firstly, I really find your book interesting and easily to follow up for a programmer who wants to know the black technology behind machine learning, Thanks a lot!!
Here is a little problem when I run part of your code under python 2:

Chapter 4 Gradient Descent:
`gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)`
in python2, '/' doesn't return float but integer number when both divisor and dividend are integer, m=100 here, 2/100 = 0, so gradients are always 0, we can fix this by changing to:
`gradients = 2.0/m * X_b.T.dot(X_b.dot(theta) - y)`

Thx :)

**Comment by ageron** [comment]
Hi @Emilio66 ! Thanks a lot, I'm really glad you find the book useful.

Good catch! Another option is to add the following line at the beginning of each of your python modules:

`from __future__ import division`

This makes Python 2 behave like Python 3 regarding division.  I think this is a slightly better option, since it encourages you to start coding like in Python 3.  I actually have the following line at the beginning of each Jupyter notebook:

`from __future__ import division, print_function, unicode_literals`

I could also add `absolute_import` to the list, but I don't need it in this project.

I thought I had added a note to the book to mention the fact that Python 2 users should add the above line to the beginning of each of their modules, but apparently I didn't, sorry about that.

I'll close this issue since it does not affect these Jupyter notebooks, but the book itself.

Thanks!
