### ISSUE TITLE
issue with 09_up_and_running_with_tensorflow section on save and restore

### ISSUE THREAD

**Issue by AEDWIP** [ageron/handson-ml#178]
Great book!

I think you may have a bug in Saving and Restoring section of https://github.com/ageron/handson-ml/blob/master/09_up_and_running_with_tensorflow.ipynb

I believe restore works because theta is in your notebook's global space. You define it in the cell above in your save example. To load and use a pretrained model you would need to not only restore but access the pretrained ops and placeholders using graph.get_tensor_by_name()

I found the following very helpful
http://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/

www.tensorflow.org seems to be incomplete

**Comment by ageron** [comment]
Hi @AEDWIP ,

Thanks for your suggestion.  You may have the first revision of my book, in which I only explained how to restore a model's variable values, not how to restore the graph structure itself, but in later revisions both solutions are explained.

Option 1: create the exact same graph as when you saved the model, then call `saver.restore()` to load the variable values (not the graph structure).

Option 2: load the graph structure using `tf.train.import_meta_graph()`, this returns a saver, and then use that saver to restore the variable values.

Indeed, the code example for option 1 just reuses the graph built above, instead of explicitly recreating it from scratch, it was more convenient that way.  The code example for option 2 is a bit below, starting at In [55].

Hope this helps!
Aurélien
