### ISSUE TITLE
Get a prediction with "theta_value"

### ISSUE THREAD

**Issue by frameproject** [ageron/handson-ml#196]
Hello,
From 09_up_and_running_with_tensorflow.ipynb in[20], how calculate a prediction with the vector theta_value ? teta0 is the first parameter of this vector ? So what are the other parameters ? 

Many thanks
Fred

**Comment by ageron** [comment]
Hi @frameproject ,
Good question, thanks for asking! Suppose you have a new instance with features x_1, x_2, ..., x_8 (there are 8 features in the dataset). The prediction is  θ_0 +  θ_1 * x_1 +  θ_2 * x_2 + ... +  θ_8 * x_8 (assuming θ is the trained parameter vector, containing the bias term θ_0 and the feature weights θ_1, θ_2, ..., θ_8).
This can be written in a shorter way as x.θ, where the dot represents the scalar product and we suppose there's an additional bias feature x_0 = 1 in the vector x.
Now if x and θ are represented as columns vector (that is, each vector is represented as a matrix with a single column), then the prediction can be rewritten as a matrix multiplication: x^T @ θ  (where ^T means "transpose of θ", that is we turn the column vector into a row vector, i.e., a matrix with a single row), and @ represents matrix multiplication. Now instead of having a scalar result, it is a matrix with a single cell containing the prediction.
Going further, if we have a matrix X containing many instances (one per row, so they are already transposed), then we can make predictions for all the instances in just one simple matrix multiplication: X @ θ.

With that, here's the answer to your question: say you have a matrix `X` containing all the instances (one per row) and the first column is full of 1s (it's all the bias features), then you can get all the predictions in one shot like this:

```python
y_pred = X.dot(theta_value)
```

Since Python 3.5, this can also be written like this:

```python
y_pred = X @ theta_value
```

The result will be a column vector with one prediction per instance.

Hope this helps!
Aurélien

**Comment by frameproject** [comment]
Merci Aurélien !

**Comment by frameproject** [comment]
Bonjour Aurélien,

I have a question about linear regression (02_end_to_end_machine_learning_project.ipynb)
In chapter 2.6.1 (in the book) the linear regression is calculated from the housing_prepared and housing_label variables. A linear regression is of the form y = teta0 + teta1 X1 + teta2 X2 ... tetan Xn.
1) I do not understand what represents the variables X1, X2 ... latititude, longitude ...? and teta the parameters of the function?
2) What is the average price of housing in this case?
3) How to display the teta parameters from the regression (lin_reg.coef_? This gives a 4x4 matrix)

Thank you for your answer, I know you are very busy.
