### ISSUE TITLE
Ch3 Binary Classification plot_precision_recall_vs_threshold

### ISSUE THREAD

**Issue by jtk622** [ageron/handson-ml#209]
I am not sure why my graph looks funky. This is only one that looks funky in the entire chapter 3. Has anyone had a similar issues? What is going on here?
![plot_precision_recall_vs_threshold curv funky](https://user-images.githubusercontent.com/31022195/38167304-3518daa8-3501-11e8-99bd-0d48a698523b.png)

**Comment by MLShooter** [comment]
my graph is just the same as yours, I haven't quite got what you mean "franky", but if you mean the wiggle part of Precision curve around threshold 1000000, I think it's normal in this case, as the author of this book has pointed out that the Precision function in terms of Threshold is really not monotonic at every little region of threshold, it may have some wavelet somewhere(for example, you improve the  threshold at someplace, and just there you do not exclude any false positive ones but have exclude a previous true positive one, that is TP/(TP + FP), TP has decrease at this point ,while FP does not change), so the curve will go down a little bit, while in the longrun, the curve will finally converge to 1.0(exclude all false positive ones).
If this explanation make any sense, I would be happy, I am happy to talk about this object and various objects in this book.

**Comment by jtk622** [comment]
Thanks @MLShooter 
Your explanation makes sense. It was just little odd that the precision is not "monotonic" only at that region around 1000000. I agree with you that it probably has to do with how the wavelets line up at that area as threshold pass over that region.

**Comment by MLShooter** [comment]
@jtk622 There may be some outlier(s) at that region around 1000000.

**Comment by ageron** [comment]
Great question! The higher the threshold, the less instances get classified as positive. Since precision is defined as the ratio of True Positives (TP) divided by the total number of Positive predictions = TP + False Positives (FP), it means that it will consider very few instances when the threshold is high. If there are a few false positives with very high scores (i.e., the model is confident that they are positive, although they are actually negative), then these FPs will have a large influence on precision when the threshold is high.  So precision is often wiggly on the high-threshold side of the graph.
On the other hand, recall is the ratio of TP divided by the number of actually positive instances (TP + FN). The number of actually positive instances is not affected by the threshold, so the curve remains smooth everywhere.
Hope this helps,
Aurélien
