### ISSUE TITLE
Chapter 2 Pipeline with DataFrames

### ISSUE THREAD

**Issue by Phusun** [ageron/handson-ml#231]
The best book on practical ML/DL in the market, hands down. You should consider teaching an online course on this topic. While exploring Pipeline feature introduced in Chapter 2, I was pleasantly surprised that Scikit-Learn now supports Pandas DataFrame in its Pipeline which will simplify some of your code. I'm a novice in Python/ML and have generally stayed away from using Pipeline due to bit of learning curve but now I'm finding it much easier to use due to it's support of DataFrame. You should consider revising the code in this chapter to directly manipulate the DataFrame as much as possible, rather than NumPy matrices. It'll help beginners like myself and others who are more familiar with Pandas.

**Comment by ageron** [comment]
Hi @Phusun ,
Thanks a lot for your kind words! I'm so sorry I just noticed your message.  I already teach an online course on the safari platform: [introduction to TensorFlow](https://www.safaribooksonline.com/live-training/courses/introduction-to-tensorflow/0636920139850/) (next session on September 4-5). I appreciate your advice. I agree that using DataFrames rather than NumPy arrays would make things simpler.  Unfortunately, although most estimators accept DataFrames as input, they usually output a NumPy array.  So even though a DataFrame could go in a pipeline, the output would still be a NumPy array.
The good news is that there is a new class `ColumnTransformer` that makes it easy to specify different transformers for different columns.  I updated the code in the notebook for chapter 2.  It means we don't have to use a `FeatureUnion` + a column-selecting transformer (`DataFrameSelector`) anymore.  It makes the code shorter and cleaner. Love it!

Thanks again,
Aurélien

**Comment by Phusun** [comment]
Looking forward to the 2nd Edition release of your book although I have gone through the first one. Will you switch to TF 2.0 in this version (I hope so!)? Will there be other major changes, new chapters etc.?
Thanks.

**Comment by ageron** [comment]
Hi Phusun,

Thanks a lot, such enthusiastic support is very motivating! :)
Yes, the 2nd edition is based on TF 2.  I'm currently writing it (just finished chapter 13). The second part of the book has a *lot* of changes, you can find the [description here](https://github.com/ageron/handson-ml/issues/334#issuecomment-469284489).
Cheers!
Aurélien

**Comment by marco82ger** [comment]
Hi,

the code written using TF2.0 will it be available? here?
thanks,
Marco

**Comment by ageron** [comment]
Hi @marco82ger ,

Yes, it is already available at https://github.com/ageron/handson-ml2 (at least for all the chapters I have already upgraded, that is chapters 1 to 13).

Hope this helps,
Aurélien

**Comment by marco82ger** [comment]
Thanks a lot!!!!

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
