### ISSUE TITLE
Chapter 2 - downloading housing data

### ISSUE THREAD

**Issue by zpsheldon** [ageron/handson-ml#234]
Hi! I'm enjoying the textbook a ton so far, I'm just having a slight issue downloading the housing data using your function fetch_housing_data, for some reason when I copy it exactly the same way into my jupyter notebook and call the function it is giving me a Certificate Verify Failed error. I'm not sure what's wrong, any tips? I'll just download and extract the csv file manually for now. Thanks!

**Comment by ageron** [comment]
Hi @zpsheldon ,

I'm glad you are enjoying the book.  :)

The SSL certificate problem is usually caused by the fact the certificates are not automatically installed with Python 3.6 on MacOSX.  Check out the comments in issue https://github.com/ageron/handson-ml/issues/143 , and check out this [answer on StackOverflow](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357).

Hope this helps,
Aurélien

**Comment by zpsheldon** [comment]
I just had to update the certificates, thank you!
