### ISSUE TITLE
chapter 3 Multiclass onevsone  classification

### ISSUE THREAD

**Issue by nitml** [ageron/handson-ml#246]
To calculate One vs one classification on SGD code used was : 

```python
sgd_clf=SGDClassifier(random_state=42)
from sklearn.multiclass import OneVsOneClassifier
ovo_clf=OneVsOneClassifier(SGDClassifier(random_state=42))
ovo_clf.fit(X_train,y_train)
ovo_clf.predict([some_digit])
```

But to evaluate this classifier following code was used : 

```
cross_val_score(sgd_clf,X_train,y_train,cv=3,scoring='accuracy')
```

why instead of `sgd_clf`, `ovo_clf` was not used?

```python
cross_val_score(ovo_clf,X_train,y_train,cv=3,scoring='accuracy')
```

**Comment by ageron** [comment]
Hi @nitml,

Thanks for your question.  The book explains that when a binary classifier is used to on a dataset with more than 2 classes, Scikit-Learn automatically uses One-versus-All.  So that's what happens when you see:

```python
cross_val_score(sgd_clf,X_train,y_train,cv=3,scoring='accuracy')
```

However, if you want to force the use of the One-versus-One strategy, you can do so using the code:

```python
sgd_clf=SGDClassifier(random_state=42)
from sklearn.multiclass import OneVsOneClassifier
ovo_clf=OneVsOneClassifier(SGDClassifier(random_state=42))
ovo_clf.fit(X_train,y_train)
ovo_clf.predict([some_digit])
```

In the book, this OvO paragraph is really just a side comment, but I agree that it is confusing in the notebook.  I'll fix this (probably next week).

Cheers,
Aurélien

**Comment by nitml** [comment]
Thank you clarifying my doubt.....I'm really enjoying reading this book...Great book for beginner like me....
