### ISSUE TITLE
Chapter 2 - FileNotFoundError message in graphics

### ISSUE THREAD

**Issue by kcng802** [ageron/handson-ml#262]
I get this error message from most of the graphics on Chapter 2:

FileNotFoundError: [Errno 2] No such file or directory: '.\\images\\end_to_end_project\\attribute_histogram_plots.png'

Using actual folder path of my laptop (Windows) in place of "." did not help - still get similar error messages.  I do get the graphic though - they are look fine.  Should I just ignore these messages?

Thanks,

**Comment by kcng802** [comment]
I found that I omitted to build the required folders.  The error messages are gone now.  Sorry.

**Comment by Hussain73** [comment]
@kcng802 how did you omit it? I am getting the same massage as well and I don;t know how to fix it.  Can you share your code please.

**Comment by ageron** [comment]
Hi @Hussain73 ,
When you clone this repository, it creates an `images` directory with a bunch of subdirectories (one per chapter), such `end_to_end_project`. If you get this error, one possibility is that you did not clone the repository, you just got the notebook and perhaps you're running it in Colab. You can fix this problem by tweaking the `save_fig()` function at the beginning of the notebook so that it creates the directory for you if it doesn't exist:

```python
def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    if not os.path.exists(IMAGES_PATH):
        os.makedirs(IMAGES_PATH)
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)
```

Hope this helps!

**Comment by Hussain73** [comment]
@ageron 
Great thanks its working now with the tweak.  However; since I am new to Jupyter, I am really interested to know how do you clone the repository?

In addition, at cell (35) code:

import matplotlib.image as mpimg
california_img=mpimg.imread(PROJECT_ROOT_DIR + '/images/end_to_end_project/california.png')
ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
                       s=housing['population']/100, label="Population",
                       c="median_house_value", cmap=plt.get_cmap("jet"),
                       colorbar=False, alpha=0.4,
                      )
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))
plt.ylabel("Latitude", fontsize=14)
plt.xlabel("Longitude", fontsize=14)

prices = housing["median_house_value"]
tick_values = np.linspace(prices.min(), prices.max(), 11)
cbar = plt.colorbar()
cbar.ax.set_yticklabels(["$%dk"%(round(v/1000)) for v in tick_values], fontsize=14)
cbar.set_label('Median House Value', fontsize=16)

plt.legend(fontsize=16)
save_fig("california_housing_prices_plot")
plt.show()

I get the following error:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-155-9ac47e6b0435> in <module>()
      1 import matplotlib.image as mpimg
----> 2 california_img=mpimg.imread(PROJECT_ROOT_DIR + '/images/end_to_end_project/california.png')
      3 ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
      4                        s=housing['population']/100, label="Population",
      5                        c="median_house_value", cmap=plt.get_cmap("jet"),

C:\Users\hp\Anaconda3\lib\site-packages\matplotlib\image.py in imread(fname, format)
   1373             return handler(fd)
   1374         else:
-> 1375             with open(fname, 'rb') as fd:
   1376                 return handler(fd)
   1377     else:

FileNotFoundError: [Errno 2] No such file or directory: './images/end_to_end_project/california.png'

**Comment by ageron** [comment]
Hi @Hussain73 ,
Thanks for your feedback.  Yeah, the error says that you are missing one file (the california.png image). Since you did not clone the repository, you are going to be missing some files again and again.
To clone the repository, you first need to have git. You can get it here: https://git-scm.com/
Git is an essential tool for all developers, so I recommend you take some time to learn it. It can get really complicated, but the basics are not too hard. There are many tutorials out there, for example [this video](https://www.youtube.com/watch?v=SWYqp7iY_Tc).
Once you have git and you understand how to use it, you can clone this repository like this:

```bash
git clone https://github.com/ageron/handson-ml.git
```

Hope this helps!

**Comment by Hussain73** [comment]
@ageron 
Thanks for your valuable feedback.  I will look into it.

**Comment by banigoamy** [comment]
Please I tried your suggestion for cell 35 and I cloned the repository but I got this warning - 'fatal: destination path 'handson-ml' already exists and is not an empty directory.'. I am also getting the error @Hussain73 got

**Comment by Murilo831** [comment]
Guys i solved it that way:

# cell 34
# Download the California image
images_path = os.path.join(PROJECT_ROOT_DIR, "images", "end_to_end_project")
os.makedirs(images_path, exist_ok=True)
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
filename = "california.png"
print("Downloading", filename)
url = DOWNLOAD_ROOT + "images/end_to_end_project/" + filename
urllib.request.urlretrieve(url, os.path.join(images_path, filename))

---------------------------------------------------
# cell 35
import matplotlib.image as mpimg
california_img=mpimg.imread(os.path.join(images_path, filename))
ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
                  s=housing['population']/100, label="Population",
                  c="median_house_value", cmap=plt.get_cmap("jet"),
                  colorbar=False, alpha=0.4)
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))
plt.ylabel("Latitude", fontsize=14)
plt.xlabel("Longitude", fontsize=14)

prices = housing["median_house_value"]
tick_values = np.linspace(prices.min(), prices.max(), 11)
cbar = plt.colorbar(ticks=tick_values/prices.max())
cbar.ax.set_yticklabels(["$%dk"%(round(v/1000)) for v in tick_values], fontsize=14)
cbar.set_label('Median House Value', fontsize=16)

plt.legend(fontsize=16)
save_fig("california_housing_prices_plot")
plt.show()

Hope this helps!

**Comment by Murilo831** [comment]
### Guys i solved it that way:
### cell 34
`# Download the California image
images_path = os.path.join(PROJECT_ROOT_DIR, "images", "end_to_end_project")
os.makedirs(images_path, exist_ok=True)
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
filename = "california.png"
print("Downloading", filename)
url = DOWNLOAD_ROOT + "images/end_to_end_project/" + filename
urllib.request.urlretrieve(url, os.path.join(images_path, filename))`

### cell 35
`import matplotlib.image as mpimg
california_img=mpimg.imread(os.path.join(images_path, filename))
ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
                  s=housing['population']/100, label="Population",
                  c="median_house_value", cmap=plt.get_cmap("jet"),
                  colorbar=False, alpha=0.4)
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))
plt.ylabel("Latitude", fontsize=14)
plt.xlabel("Longitude", fontsize=14)

prices = housing["median_house_value"]
tick_values = np.linspace(prices.min(), prices.max(), 11)
cbar = plt.colorbar(ticks=tick_values/prices.max())
cbar.ax.set_yticklabels(["$%dk"%(round(v/1000)) for v in tick_values], fontsize=14)
cbar.set_label('Median House Value', fontsize=16)

plt.legend(fontsize=16)
save_fig("california_housing_prices_plot")
plt.show()`

### Hope this helps!

**Comment by Murilo831** [comment]
Guys i solved it that way:
cell 34 code:
```
# Download the California image
images_path = os.path.join(PROJECT_ROOT_DIR, "images", "end_to_end_project")
os.makedirs(images_path, exist_ok=True)
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
filename = "california.png"
print("Downloading", filename)
url = DOWNLOAD_ROOT + "images/end_to_end_project/" + filename
urllib.request.urlretrieve(url, os.path.join(images_path, filename))
```
cell 35 code:
```import matplotlib.image as mpimg
california_img=mpimg.imread(os.path.join(images_path, filename))
ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
                  s=housing['population']/100, label="Population",
                  c="median_house_value", cmap=plt.get_cmap("jet"),
                  colorbar=False, alpha=0.4)
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))
plt.ylabel("Latitude", fontsize=14)
plt.xlabel("Longitude", fontsize=14)

prices = housing["median_house_value"]
tick_values = np.linspace(prices.min(), prices.max(), 11)
cbar = plt.colorbar(ticks=tick_values/prices.max())
cbar.ax.set_yticklabels(["$%dk"%(round(v/1000)) for v in tick_values], fontsize=14)
cbar.set_label('Median House Value', fontsize=16)

plt.legend(fontsize=16)
save_fig("california_housing_prices_plot")
plt.show()
```
Hope this helps!

**Comment by Murilo831** [comment]
Guys i solved it that way:
cell 34 code
```ruby
# Download the California image
images_path = os.path.join(PROJECT_ROOT_DIR, "images", "end_to_end_project")
os.makedirs(images_path, exist_ok=True)
DOWNLOAD_ROOT = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
filename = "california.png"
print("Downloading", filename)
url = DOWNLOAD_ROOT + "images/end_to_end_project/" + filename
urllib.request.urlretrieve(url, os.path.join(images_path, filename))
```
cell 35 code:
```ruby
import matplotlib.image as mpimg
california_img=mpimg.imread(os.path.join(images_path, filename))
ax = housing.plot(kind="scatter", x="longitude", y="latitude", figsize=(10,7),
                  s=housing['population']/100, label="Population",
                  c="median_house_value", cmap=plt.get_cmap("jet"),
                  colorbar=False, alpha=0.4)
plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5,
           cmap=plt.get_cmap("jet"))
plt.ylabel("Latitude", fontsize=14)
plt.xlabel("Longitude", fontsize=14)

prices = housing["median_house_value"]
tick_values = np.linspace(prices.min(), prices.max(), 11)
cbar = plt.colorbar(ticks=tick_values/prices.max())
cbar.ax.set_yticklabels(["$%dk"%(round(v/1000)) for v in tick_values], fontsize=14)
cbar.set_label('Median House Value', fontsize=16)

plt.legend(fontsize=16)
save_fig("california_housing_prices_plot")
plt.show()
```

Hope this helps!

**Comment by ageron** [comment]
I recently updated all the notebooks in this repository to ensure they can be run without having to clone repository: the code just downloads data when it's required. In fact, I added a link to Colab at the beginning of each notebook, so you can now run the notebooks without installing anything on your machine.
Hope this helps!
