### ISSUE TITLE
Typo in Chapter 14

### ISSUE THREAD

**Issue by yc-Chen1994** [ageron/handson-ml#268]
In "Equation 14-1. Output of a recurrent layer for a single instance":
the weight vector should be "w" (not capitalized) since x and y are single
instances.

**Comment by ageron** [comment]
Hi @yc-Chen1994 ,

Thanks for your feedback.  There is a single instance, but many neurons, which is why it's a weight matrix and not a weight vector (there is one weight vector per neuron, and all these weights are merged into a single matrix). The paragraph before equation 14-1 explains this:

> Each recurrent neuron has two sets of weights: one for the inputs **x**_(_t_) and the other for the outputs of the previous time step, **y**_(_t–1_). Let’s call these weight vectors **w**_x and **w**_y. If we consider the whole recurrent layer instead of just one recurrent neuron, we can place all the weight vectors in two weight matrices, **W**_x and **W**_y.

Hope this helps,
Aurélien

**Comment by yc-Chen1994** [comment]
Ok, I got it, thanks!
