### ISSUE TITLE
Chapter 10 Using dense() instead of neuron_layer()

### ISSUE THREAD

**Issue by denseuropa** [ageron/handson-ml#271]
I'm trying to create a stand alone routine analogous to In[26] and In[27] for this section without running all of the previous sections.  If I use just In[26] it fails with: ValueError: Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph. Pass an explicit session to `eval(session=sess)`.

Adding the construction phase before In[26] the following:
from In[30] to In[36] removing the line init = tf.global_variables_initializer(),
In[24], and inserting In[10] after In[31]  
it works as expected however this requires the download (X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data(). 
If I comment out this line it fails on the next line with X_train not being found. 
If I comment out all of In[10]  it fails at X_new_scaled = X_test[:30] with X_test not defined.

I'm sure there must be a way to load a saved ckpt file and perform a prediction without reloading the MNIST data.

**Comment by ageron** [comment]
Hi @denseuropa ,

Thanks for your question. The simplest option is to load the graph structure itself using `tf.train.import_meta_graph()`. Here is some code that you can put just before In[26] and you don't have to run any other code before that:

```python
import tensorflow as tf
import numpy as np

saver = tf.train.import_meta_graph("./my_model_final.ckpt.meta")
X = tf.get_default_graph().get_tensor_by_name("X:0")
logits = tf.get_default_graph().get_tensor_by_name("dnn/outputs/add:0")
X_test = np.random.rand(20, 28*28)
```

Then you can run cell In[26]:

```python
with tf.Session() as sess:
    saver.restore(sess, "./my_model_final.ckpt") # or better, use save_path
    X_new_scaled = X_test[:20]
    Z = logits.eval(feed_dict={X: X_new_scaled})
    y_pred = np.argmax(Z, axis=1)
```

Let me explain the code above:
* First, we have the imports.
* Then the `import_meta_graph()` function loads the graph structure into the default graph and returns a saver that can be used to load the variable values (during the execution phase). 
* Then you need to get a reference to the `logits` and the inputs `X` if you want to be able to make predictions, and for that you can use `graph.get_tensor_by_name()`.  The tricky part here is to know what names to use. The name of a tensor is always the name of the operation that outputs it followed by `:0` if it is the first output, `:1` if it is the second, and so on.  This is why you can get `X` by name using `graph.get_tensor_by_name("X:0")`.
* For the logits, it is a bit trickier since it is the output of a dense layer named `"outputs"`, which is in a name scope named `"dnn"`. So the name starts with `"dnn/outputs"`. However, a dense layer has multiple tensors inside it, and it is a bit hard to know which one is the output of the layer. The simplest solution is to just run the code before (once) and print the name of the `logits` tensor. Another approach is to look at the graph in TensorBoard. Anyway, at the end you will find that the output tensor of a dense layer is the tensor named `"add"`. So the full name of the `logits` tensor is `"dnn/outputs/add:0"`.
* Finally, we need some test data, and here we just create random images. Of course if you wanted to actually use this model for digit classification, you would have to process the images so that they are grey-scale 28x28 images, and you would pass them instead of random images.

Hope this helps,
Aurélien

**Comment by denseuropa** [comment]
Aurélien

Thanks for the rapid response, I must admit I thought after extensive Googeling I had tried all of the all of the possible ways of using the import meta and get_tensor routines Your explanation helps however:


KeyError                                  Traceback (most recent call last)
<ipython-input-6-b7b8c6ada9cb> in <module>()
      4 save = tf.train.import_meta_graph("./my_model_final.ckpt.meta")
      5 X = tf.get_default_graph().get_tensor_by_name("X:0")
----> 6 logits = tf.get_default_graph().get_tensor_by_name("dnn/outputs/add:0")
      7 X_test = np.random.rand(20, 28*28)

KeyError: "The name 'dnn/outputs/add:0' refers to a Tensor which does not exist. The operation, 'dnn/outputs/add', does not exist in the graph."

I re-ran the sections to do the extract and that worked. I'm sure this will be obvious to me eventually


Dennis

**Comment by ageron** [comment]
Mmmh, that's odd, perhaps it's because we don't have the same version of TensorFlow and the tensors are named differently? I suggest you run the cells up to In[25] and print the name of the logit tensor:

```python
print(logit.name)
```

Then use that name instead of `"dnn/outputs/add:0"`.

Hope this helps,
Aurélien

**Comment by ageron** [comment]
Great! I'm glad this is fixed.  I just upgraded to TF 1.10.0-rc1, and now I see the name is `BiasAdd` instead of `add`, so apparently they renamed it.
