### ISSUE TITLE
chapter 11 Question 8 part 1 making hidden layer 

### ISSUE THREAD

**Issue by nitml** [ageron/handson-ml#280]
in question 8 to make hidden layer code used written was:

```python
he_init=tf.variance_scaling_initializer()

def dnn(inputs,n_hidden_layers=5,n_neurons=100,name=None,
       activation=tf.nn.elu,initializer=he_init):
    with tf.variable_scope(name,"dnn"):
        for layer in range(n_hidden_layers):
            inputs=tf.layers.dense(inputs,n_neurons,activation=activation,
                               kernel_initializer=he_init,name="hidden%d" %(layer+1))
    return inputs
```

Why have we used `tf.Variable_scope()` ? why can't we use `tf.name_scope()` in line 4 ?

**Comment by ageron** [comment]
Hi @nitml ,

It depends on whether or not you plan to share variables across your graph or not. In this graph we, don't need this, so you could indeed replace the variable_scope with a name_scope.

Hope this helps,
Aurélien

**Comment by amoat7** [comment]
Thanks for the answer.  However the tensorboard graphs for using variable_scope and name_scope do not look similar.

**Comment by ageron** [comment]
Thanks for your feedback @amoat7 . Since TF 2.0 will drop `variable_scope()` entirely, I recommend moving to `name_scope()`. More generally, try to use tf.keras as much as possible, and if needed create some custom layer (see my [TF 2.0 notebooks](https://github.com/ageron/tf2_course) for more details).
Hope this helps,
Aurélien

**Comment by ageron** [comment]
Closing stale issues. Please reopen if you are still experiencing a problem.
