### ISSUE TITLE
Math - Linear Algebra

### ISSUE THREAD

**Issue by stuartpaterson480** [ageron/handson-ml#289]
Small issue but I'll report it anyway: There are several "Unknown characters" in the text at the start of the dot product part of the Linear Algebra notebook.
Thanks for providing a helpful resource.

**Comment by ageron** [comment]
Hi @stuartpaterson480 ,

Thanks for your kind words and your feedback.  This issue is actually a bug in github's Jupyter notebook viewer (see [this issue](https://github.com/jupyter/nbviewer/issues/452) for more examples).  If you open this notebook with your own Jupyter server, or if you use [Jupyter's notebook viewer](http://nbviewer.jupyter.org/github/ageron/handson-ml/blob/master/math_linear_algebra.ipynb), then everything should be fine.

Hope this helps,
Aurélien
