### ISSUE TITLE
Book page 85 missing code

### ISSUE THREAD

**Issue by julianpraxis** [ageron/handson-ml#31]
This code is in cell [22] of the notebook but does not appear on page 85 of the book.
y_train_perfect_predictions = y_train_5

@ageron What is the best way to let you know of items such as this one? I am going through the book in a very methodical, slow manner; hence, I might find things that you might want to know about.

**Comment by Praveen-Gupta** [comment]
There is one errata page mentioned at book URL page. This one is already
mentioned there.
Check
http://www.oreilly.com/catalog/errata.csp?isbn=0636920052289

**Comment by julianpraxis** [comment]
@Praveen-Gupta OK. Thank you. I will report "errors" I find in the book to the book's page at O'Reilly.

**Comment by ageron** [comment]
Thanks for your feedback @julianpraxis, and thanks @Praveen-Gupta for the helpful link.

For problems concerning the notebooks, filing a GitHub issue is the best option.  For problems concerning the book, then the errata page that Praveen pointed to is the best option.

You'll find lots of content in the notebook that does not appear in the book. In general, it is on purpose, because the text explains something, and I want to keep the code as concise as possible, for readability. I understand that people may wonder where these "perfect predictions" come from, but if I write "y_train_perfect_predictions = y_train_5" I'm afraid other people may wonder why I'm writing this? The idea was that a perfect model, if you can train one, will give you a diagonal confusion matrix.

Hope this helps,
Aurélien
