### ISSUE TITLE
housing data/ ocean_proximity question

### ISSUE THREAD

**Issue by ktorresSD** [ageron/handson-ml#310]
Hi, I intend to use this dataset for a school project using multiple regression to predict house price.
I see you said "An additional categorical attribute called ocean_proximity was added, indicating (very roughly) whether each block group is near the ocean, near the Bay area, inland or on an island. This allows discussing what to do with categorical data." Can we talk a little bit about what was done to determine this?

Thank you!

**Comment by r-ichi** [comment]
The creator of the dataset could answer that question, but remember that the dataset is from the 80's or so...

**Comment by ageron** [comment]
Hi @ktorresSD ,
I really happy that you are using this dataset for a school project! :)
The process for adding the ocean_proximity column was pretty manual: I just wrote a few rules (e.g., if longitude between X and Y then ocean_proximity="NEAR OCEAN", if distance to lat/long of bay area, then ocean_proximity="NEAR BAY", etc.).  I really didn't try to be very precise, as my goal was to have a dataset with a categorical attribute, not really to try to solve the california housing problem.
I hope this helps and that your school project will be successful!

**Comment by hlbglobal** [comment]
I have a couple of questions.  Number 1:  The ocean_proximity categorical variable is this considered to be an ordinal variable with inland being the worst one but nearness to ocean making it ordinal?  If it is supposed to be ordinal and not just nominal I don't really know which one of these is higher than the other. If it is just nominal that makes it easier because I think I could just use get_dummies to make it numeric.

Question 2)  Is there a program to use where you can input a couple of thousand lat/long pairs and get a district name or something similar as output?  I know they should really be relevant to the housing price but it's hard to tell if those are justs separate variables.  Thanks very much for your help, Barbara Dilucchio

**Comment by ageron** [comment]
Hi @hlbglobal ,
Sorry for the late response, I was traveling.
Question 1: the `ocean_proximity` categorical variable is meant to be nominal.  You could use `get_dummies()` but then you would need to keep track of the mapping used by Pandas, so that the same mapping would be used for new instances. This is why it's probably easier to use the `OneHotEncoder` class (from Scikit-Learn 0.20+, not from older versions).
Question 2: I'm guessing you could use the Google Maps API, or perhaps OpenStreetMap.
Hope this helps

**Comment by ageron** [comment]
Closing stale issue. Please reopen if the problem persists.
