### ISSUE TITLE
Understanding Custom Transformers

### ISSUE THREAD

**Issue by devinwhalen** [ageron/handson-ml#316]
Hey,

I am not sure if this is the correct place to ask this question but I am stuck understanding a section of the code in the custom transformer:

def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, household_ix]
        population_per_household = X[:, population_ix] / X[:, household_ix]

These are probably basic python questions but I am new to python so I keep getting tripped up on python code.

1) What type of object is "X"?
2) What does this do: X[:, rooms_ix]
  I don't know how to look that up to understand what it is doing?  Is that a slice of a matrix?  Is it returning only that column in each row?

**Comment by devinwhalen** [comment]
I read over the notebook on github and now it makes more sense.  This wasn't clear in the book but in the notebook you pass in housing.values, which is a Numpy array and the syntax:
X[:,rooms_ix] means all rows but only the rooms_ix column.

I think I need a better handle on numpy and pandas in order to understand your examples.

Thanks

**Comment by ageron** [comment]
Hi @devinwhalen ,
Sorry for the late response, I was traveling. I'm glad you figured it out, and I hope you are enjoying the rest of the book.

**Comment by ankit5294** [comment]
Hi @ageron ,

Thanks a ton for the book! It is an extremely helpful resource for understanding the basics of Machine Learning for an absolute beginner like me.

I apologize for the question I am about to ask, since it could be very basic and could have even arose because of my ignorance.

Can you please explain the parameter y=None and its significance in the functions within transformer classes and in general?

Appreciate your help and thanks again for the book!

**Comment by ageron** [comment]
Hi @ankit5294 ,
Happy New Year, and thanks for your kind words, I'm glad you find my book useful! Regarding `y=None`, I think you are referring to the fact that we set `y=None` in the `fit()` method when we define custom transformers. This is because `Pipeline` objects expect every object in the pipeline to have a `fit()` method with at least two arguments, `x` and `y`.  So even though we don't really need this argument for the transformer itself, we must add it anyway so that it will work in pipelines.
Hope this helps!

**Comment by ankit5294** [comment]
Wish you and your family a very Happy New Year too!!

Thanks for the reply. My doubt has been resolved! :)
