### ISSUE TITLE
Chapter 14 Building a RNN

### ISSUE THREAD

**Issue by jetychill** [ageron/handson-ml#323]
Hey Aurelien i want to first thank you for the great book i can't wait for your second edition.
i am having a lot of issues with building a rnn with anything else but the data specified in your book mnist and time-series data those work fine but when i try it with my data i get a multitude of errors a few which i solved however now i am well and truly stuck, this is the error :  

```python
InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[50,2] labels_size=[25,2]
```

here is my entire code, the data is a pandas df that was pickled so i don't have to do work on it every time i run the program 

```python
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import tensorflow as tf 

n_steps = 5
n_inputs = 11
n_neurons = 150
n_outputs = 2
batch_size = 50
n_epochs = 30
learning_rate = 0.001
mr_scaler = StandardScaler()

X_data_test = pd.read_pickle('X_data_test.pickle')
y_data_test = pd.read_pickle('y_data_test.pickle')
X_data_train = pd.read_pickle('X_data_train.pickle')
y_data_train = pd.read_pickle('y_data_train.pickle')
X_forward = pd.read_pickle('X_forward.pickle')
y_forward = pd.read_pickle('y_forward.pickle')
y_data_train = y_data_train.values.reshape((-1,1))

#X_data_train = mr_scaler.fit_transform(X_data_train)
#X_data_test = mr_scaler.fit_transform(X_data_test)
#X_forward = mr_scaler.fit_transform(X_forward)




X = tf.placeholder(tf.float32,[None,n_steps,n_inputs])
y = tf.placeholder(tf.int32,[None,n_steps,n_outputs])

basic_cell = tf.contrib.rnn.OutputProjectionWrapper(tf.contrib.rnn.BasicRNNCell(num_units=n_neurons),output_size = n_outputs)
outputs,states = tf.nn.dynamic_rnn(basic_cell,X,dtype=tf.float32)

logits = tf.layers.dense(outputs,n_outputs)
print(tf.shape(logits))

xenotropy = tf.nn.softmax_cross_entropy_with_logits(labels=y,logits=logits)
loss= tf.reduce_mean(xenotropy)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)

logits_res = tf.reshape(logits, (-1, n_outputs))
logits_res = tf.squeeze(logits_res)
y_res = tf.reshape(y, (-1,n_outputs))
y_res = tf.squeeze(y_res)

correct_res = tf.nn.in_top_k(logits_res, y_res, 1)
correct = tf.reshape(correct_res, (-1, n_steps))


accuracy = tf.reduce_mean(tf.cast(correct,tf.float32))

init = tf.global_variables_initializer()




def fetch_batch(epoch, batch_index, batch_size):
    np.random.seed(epoch * n_batches + batch_index)
    indices = np.random.randint(len(X_data_train), size=batch_size)
    X_batch = X_data_train.values[indices]
    y_batch = y_data_train[indices]
    return X_batch, y_batch

n_batches = int(np.ceil(len(X_data_train/batch_size)))

with tf.Session() as sess:
	init.run()
	for epoch in range(n_epochs):
		for iteration in range(n_batches):
			X_batch,y_batch = fetch_batch(epoch,iteration,batch_size)
			X_batch = X_batch.reshape((-1,n_steps,n_inputs))
			y_batch = y_batch.reshape((-1,n_steps,n_outputs))
			sess.run([training_op],feed_dict={X:X_batch,y:y_batch})
		acc_train = accuracy.eval(feed_dict={X:X_batch,y:y_batch})
		acc_val = accuracy.eval(feed_dict={X:X_data_test,y:y_data_test})
		acc_forward = accuracy.eval(feed_dict={X:X_forward,y:y_forward})
		summary_str = accuracy_summary.eval(feed_dict={X:X_data_test,y:y_data_test})
		file_writer.add_summary(summary_str,epoch)
		print(epoch, ' Train accuracy: ',acc_train, ' Val accuracy:',acc_val,' Forward Accuracy',acc_forward)
```

I really hope you can help me  thanks :)

**Comment by ageron** [comment]
Hi @jetychill ,
Thanks for your kind words and your question. I will look into this issue this week.

**Comment by ageron** [comment]
I need some details on the data and what you are trying to do, please. As far as I understand, you want to perform binary classification on sequences of 5 time steps each, where each time step is 11 dimensional, is that correct?

If so, then the simplest way to go is to use the Keras API, something like this:

```python
import tensorflow as tf
import numpy as np

n_steps = 5
n_inputs = 11
n_neurons = 150

# Fake data
X_train = np.random.randn(10000, n_steps, n_inputs)
y_train = np.random.randint(low=0, high=2, size=10000)
X_valid = np.random.randn(1000, n_steps, n_inputs)
y_valid = np.random.randint(low=0, high=2, size=1000)
X_test = np.random.randn(2000, n_steps, n_inputs)
y_test = np.random.randint(low=0, high=2, size=2000)

model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(n_neurons, input_shape=[n_steps, n_inputs]))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=16, epochs=10, validation_data=(X_valid, y_valid))
score = model.evaluate(X_test, y_test, batch_size=16)
```

Note that TensorFlow 2.0 will be out within the next few months, and it will strongly push users to migrate to Keras when using RNNs (read more about this [here](https://github.com/qlzh727/community/blob/e3b2f4fb7022ac90f29e4895257015fef896083b/rfcs/20180920-unify-rnn-interface.md)). For more details on TF 2.0, you can check out my [YouTube video](https://youtu.be/WTNH0tcscqo) on this topic.

However, if you want to stick to using the `tf.nn.rnn_cell` API, or you just want to understand what you got wrong, then (still assuming you want to do binary classification of sequences) your neural network should just output a single probability for each sequence, not two probabilities per time step, so the final output shape should be [None, 1]. So this line looks suspicious to me:

```python
y = tf.placeholder(tf.int32,[None,n_steps,n_outputs])
```

I would expect something like this:

```python
n_outputs = 1
y = tf.placeholder(tf.int32, [None, n_outputs])
```

Next, you don't need the `OutputProjectionWrapper` in this case (again, assuming you want to do binary classification). Indeed, all it does is reduce the dimensionality of the output at each time step. But since you only care about the output at the last time step, it's a waste of resource to reduce the dimensionality at each time step. So I would define `basic_cell` like this (also note that `tf.contrib.rnn` was moved to the core API, so you should use `tf.nn.rnn_cell` instead):

```python
basic_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=n_neurons)
```

Next, you should probably use `states` instead of `outputs`, since you don't need the outputs at each and every time step, only at the last time step. In the case of the `BasicRNNCell`, the `states` is just equal to the outputs at the last time step). Alternatively, you could use `outputs[:, -1]` instead of `outputs`.

Hope this helps,
Aurélien

**Comment by jetychill** [comment]
Hey Aurelien thank you for the in depth answer it helped me further understand the basics of how a RNN works, i did actually end up using the Keras api and a data generator to feed the sequences i honestly can't see myself going back to plain old tensorflow, but since we are at that topic do you think that using the Keras Api limits me in anyway, performance wise or limits the amount of customization of a network.

Thanks again

**Comment by ageron** [comment]
I'm glad I could help.  I used to think that Keras limited me for some exotic architectures (for example, when building Capsule Networks, see my [video](https://www.youtube.com/watch?v=pPN8d0E3900) on this topic), but it has been more and more integrated into TensorFlow, and now I can't live without it.  The TensorFlow team probably felt the same way, because they clearly promote it in TF 2.0.  I don't think it will limit you in any way.  If you need something really exotic, you can always write your own custom layer.
