### ISSUE TITLE
Solutions to ch15

### ISSUE THREAD

**Issue by s1782662** [ageron/handson-ml#363]
Hi Aurelien,

I know you are busy. If time permits can you upload the solutions to chapter 15. Thanks. Pardon me to ask this, did you include any new materials to version 2 of this book **Hands-On Machine Learning with Scikit-Learn & TensorFlow.**

**Comment by ageron** [comment]
Hi @s1782662 ,
Yes, I'm sorry there are still a few missing exercise solutions in the book, I never had time to do them. I'm  writing the 2nd edition of the book right now, so that's my priority, but when it's over I'll have time to work on the exercise solutions. In the 2nd edition:
* chapters 1 to 8 (introduction to Machine Learning using Scikit-Learn) are mostly the same, except I updated them to the latest versions of all libraries (e.g., using Scikit-Learn 0.20's `ColumnTransformer` class rather than the current mix of `FeatureUnion`, `Pipeline` and custom transformers).
* I added a new chapter on Unsupervised Learning techniques (clustering, novelty and anomaly detection, mixture models...).
* chapters 9 (intro to tensorflow) is completely rewritten for TensorFlow 2.0. I also moved it to be after the new tf.data chapter.
* chapters 10 (intro to neural nets) is about 50% rewritten to introduce the Keras API and TensorFlow 2.0's implementation (tf.keras) and use it to build the first neural nets.
* chapter 11 (techniques to build deep nets) is about 50% rewritten to use high-level TF code (i.e., tf.keras) instead of low-level code.
* chapter 12 (distributed TensorFlow) is completely rewritten and pushed to the end of the book. It also contains more info on deployment (to GCP, mobile...).
* There's a new chapter on loading & preprocessing data with tf.data and TFRecords.
* Chapters 13, 14, 15 and 16 (CNNs, RNNs, Autoencoders and Reinforcement Learning) will probably be about 50% rewritten to use TensorFlow 2.0. I also plan to add more examples and more content (e.g., on object detection, semantic segmentation, GANs, etc.)

In short, the first part has changed little expect for a new chapter on unsupervised learning, but the second part has huge changes, due to the fact that (1) TensorFlow 2.0 is a big change, (2) Deep Learning is a fast-moving field.

Hope this helps
