### ISSUE TITLE
Chapter 9 manual computation of gradients integer division...

### ISSUE THREAD

**Issue by dataforager** [ageron/handson-ml#38]
Hi Aurelien,

   Been getting through your (excellent) book, and I noticed that for the manual computation of the gradients section of chapter 9 I was getting gradients of 0 (no learning). It looked like the offending line was: gradients = 2/m * tf.matmul(tf.transpose(X), error) where 2/m is an integer division resulting in 0.

When I switched the 2 to float notation (so, 2.), the gradients were being updated accordingly and everything seemed to work.

Take care.
Michael

**Comment by ageron** [comment]
Hi @dataforager,

Thanks for your feedback!  Indeed, I wrote this code for Python 3, which defaults to float division. However, everything should work fine in Python 2 as well if you add the following line at the beginning of your Python files:

```python
# To support both python 2 and python 3
from __future__ import absolute_import, division, print_function, unicode_literals
```

The Jupyter notebooks include this line at the very beginning, so they actually work fine in both Python 2 and 3.

Since Python 2 is now deprecated, I recommend switching to Python 3, or at least preparing for it. One way to prepare for migration is to start writing code that works on both Python 2 and Python 3. Some libraries like `six` or `future` can help a lot. In fact, I recommend you go through this excellent [Python 2/3 compatibility cheat sheet](http://python-future.org/compatible_idioms.html). It shows how to write code that works on both Python 2 and 3.

The starting point is to add the `from __future__` line above at the beginning of all your Python files, then run your tests and fix all the errors you find: you will likely need to replace a few `/` with `//` if you expect integer division, you will need to fix all your `print` statements (e.g. replace `print "hi"` with `print("hi")`, and so on), and most importantly you will need to fix a bunch of unicode _vs_ byte string errors.  But once that's done your code will be much easier to migrate to Python 3, when the time comes.

That said, I think you are right that the book should mention this fact. Right now it just says "The latest version of Python 3 is recommended. Python 2.7+ should work fine too, but it is deprecated." I will add "If you use Python 2, you must add `from __future__ import division, print_function, unicode_literals` at the beginning of your Python files."

I hope this helps,
Aurélien
