### ISSUE TITLE
Ch8 Dimensionality Reduction: broken link

### ISSUE THREAD

**Issue by dvklopfenstein** [ageron/handson-ml#382]
Thank you for a wonderful book. I have already placed my order for the 2nd edition.

In the first edition, on page 212, the link in the following the sentence is broken:

**This is the rather simple idea behind PCA (http://goo.gl/gbNo1D)**

**Comment by ageron** [comment]
Thanks @dvklopfenstein, I really appreciate your support! :)

In the latest release, I replaced all the goo.gl links with homl.info links. Firstly because goo.gl is being shutdown by Google (old links should still work, but no way to create new ones), and second because it's impossible to change a goo.gl link, while I own homl.info so I can fix the links if they break.  I replaced this particular link with https://homl.info/31, it leads to a Google scholar search query, because unfortunately this paper does not seem to be hosted online on a stable server.

Cheers!

**Comment by dvklopfenstein** [comment]
Sounds great. Thank you again for a great book and all of your code.
