### ISSUE TITLE
Ch8: High dimensionality description

### ISSUE THREAD

**Issue by dvklopfenstein** [ageron/handson-ml#383]
Thank you so much for your incredible book and your code. I have already ordered and paid for Edition 2.

In the beginning of Chapter 8 (Dimensionality Reduction), might it be possible to add more to the statement on page 207 for edition 2?:

_This fact implies that high-dimensional datasets are at risk of being very sparse_ 

That entire paragraph is intriguing, but causes more questions than answers for me. Can you add further description and perhaps add references you find helpful to other material? My datasets have extremely high dimensionality.

**Comment by ageron** [comment]
Thanks @dvklopfenstein , I'm really glad you enjoyed my book.  :)

What I mean by "sparse dataset" in this context is that the instances are likely to be very distant from each other, on average. For example, let's compare the mean distance between all the instances in a random dataset, for a 1-dimensional dataset, 2-dimensional, and so on:

```python
import numpy as np
from scipy.spatial import distance_matrix

def mean_distance(n_instances, n_dims):
    X = np.random.rand(n_instances, n_dims)
    return distance_matrix(X, X).mean()

for n_dims in (1, 2, 3, 10, 20, 30, 100, 200, 300):
    print("#dims: {:3d}, mean distance: {:.2f}".format(n_dims, mean_distance(1000, n_dims)))
```

This outputs:

```
#dims:   1, mean distance: 0.34
#dims:   2, mean distance: 0.52
#dims:   3, mean distance: 0.66
#dims:  10, mean distance: 1.27
#dims:  20, mean distance: 1.81
#dims:  30, mean distance: 2.22
#dims: 100, mean distance: 4.08
#dims: 200, mean distance: 5.76
#dims: 300, mean distance: 7.06
```

As you can see, the higher the dimensionality, the greater the mean distance between 2 instances. There's more and more "space" between the instances as the dimensionality grows. Surprisingly, even though I'm only generating instances in the unit hypercube (all features are between 0 and 1), the mean distance at 300 dims is 7! It's a bit surprising until you realize that a 2D square has a diagonal longer than 1, so it's possible for instances in a unit square to be more than 1 unit apart. If you increase the dimensionality, you need exponentially more training examples to preserve the same density of training examples.

When a machine learning algorithm learns a pattern based on an instance, our hope is that this pattern can generalize to near-by instances. But since instances are very far away from each other in high-dimensional datasets, it is harder to generalize, so the performance of an ML algorithm will decrease. The two things that can save us is (1) if we add a lot of training data, reducing the mean distance between the training instances, or (2) if we can reduce the dataset's dimensionality. Fortunately, real-life training sets are often not as high-dimensional as they seem: this is the "manifold hypothesis". For example, there are 2 to the power of 784 possible 28x28 images with pixels either on or off. This is a *huge* number, far beyond the number of atoms in the observable universe, yet only a tiny, tiny fraction look like anything else than noise, and an even tinier fraction look like digits. If we can reduce the dataset to the small number of dimensions that are actually useful to describe a hand-written digit, then we can escape from the curse of dimensionality.

Does this helps?

**Comment by dvklopfenstein** [comment]
Yes. That certainly helps. Thank you for the example in code too.

Can't wait for your next edition!
