### ISSUE TITLE
Ch7 question about Adaboost algorithm. 

### ISSUE THREAD

**Issue by qiaozhi9092** [ageron/handson-ml#384]
Hi Aurélien,
In equation 7-3 where the weight for each instance is updated. I am wondering why the weight for the correctly classified instance does not get reduced? 

According to the book, the new weight for the correctly classified instance will just be the same as its predecessor's. Of course as long as the weight for the misclassified instances get boosted, even if the weight for the correctly classified instances stay the same, after all the weights get normalized, the algorithm will work.  
However I have looked up some other sources, all of them used an equation similar to this one: 
![1_mqLcX8yookiPVZoAe6iwqA](https://user-images.githubusercontent.com/10824922/54793693-da701400-4c00-11e9-8fdc-d38b23dbdf81.jpeg)
(https://towardsdatascience.com/boosting-algorithm-adaboost-b6737a9ee60c)
where w_m(x_i, y_i) is the old weight for the instance m, theta_m is the predictor's weight, y_i*f_m(x_i) determines whether the instance is correctly classified or not, and Z_m is the sum of all the weights. 

According to this equation, the weights for the incorrectly classified instances will get boosted and the weights for the correctly classified instances will get reduced. 

Can you help me to clarify the difference between the algorithm in the book and the algorithm I mentioned above? Or perhaps they will result in similar outcomes so either way should be fine? 

Thanks for your help!
Best,

**Comment by ageron** [comment]
Hi @qiaozhi9092 ,

Great question! It's actually mathematically equivalent:

* replace _m_ with _j_
* replace _w_<sub>_m_+1</sub>(_x_<sub>_i_</sub>, _y_<sub>_i_</sub>) = _w_<sub>_m_</sub>(_x_<sub>i</sub>, _y_<sub>i</sub>)... with _w_<sup>(i)</sup> &larr; _w_<sup>(i)</sup>...
* replace _θ_<sub>_m_</sub> with 0.5&alpha;<sub>_j_</sub>
* replace _y_<sub>i</sub> _f_<sub>_m_</sub>(_x_<sub>i</sub>) with 1 if classifier is correct, or -1 otherwise.
* replace _Z_<sub>_m_</sub> with _Z_

Suppose we have three instances: one is correctly classified, the other two misclassified. With the equation you propose (converting into my notations, as explained above), we get:

_w_<sup>(1)</sup> &larr; _w_<sup>(1)</sup> exp(-0.5&alpha;<sub>_j_</sub>) / Z
_w_<sup>(2)</sup> &larr; _w_<sup>(2)</sup> exp(0.5&alpha;<sub>_j_</sub>) / Z
_w_<sup>(3)</sup> &larr; _w_<sup>(3)</sup> exp(0.5&alpha;<sub>_j_</sub>) / Z
where Z = _w_<sup>(1)</sup> exp(-0.5&alpha;<sub>_j_</sub>) + _w_<sup>(2)</sup> exp(0.5&alpha;<sub>_j_</sub>) + _w_<sup>(3)</sup> exp(0.5&alpha;<sub>_j_</sub>)

Let's multiply both the numerator and the denominator by exp(0.5&alpha;<sub>_j_</sub>):

_w_<sup>(1)</sup> &larr; _w_<sup>(1)</sup> / Z
_w_<sup>(2)</sup> &larr; _w_<sup>(2)</sup> exp(&alpha;<sub>_j_</sub>) / Z
_w_<sup>(3)</sup> &larr; _w_<sup>(3)</sup> exp(&alpha;<sub>_j_</sub>) / Z
where Z = _w_<sup>(1)</sup> + _w_<sup>(2)</sup> exp(&alpha;<sub>_j_</sub>) + _w_<sup>(3)</sup> exp(&alpha;<sub>_j_</sub>)

Now you can see we get the exact same as equations as 7-3. I just think it looks better this way. ;-)

Note that in their post they define:
_&theta;_<sub>_m_</sub> = 0.5 * log((1 - _&epsilon;_<sub>_m_</sub>)/_&epsilon;_<sub>_m_</sub>)
while I define:
&alpha;<sub>_j_</sub> = &eta; log((1 - _r_<sub>_j_</sub>)/_r_<sub>_j_</sub>)
So since we replaced _θ_<sub>_m_</sub> with 0.5&alpha;<sub>_j_</sub>, it implies that they are using &eta; = 1.

**Comment by qiaozhi9092** [comment]
Hi @ageron,

Thank you so much for the prompt and detailed explanation. I followed your derivation and now I totally understand why you wrote equation 7-3 the way it is. For a similar question in the future, I will try some general cases like you did and maybe I could figured it out myself :)

I am almost done with the first part of the book, and I cannot wait to get started on the second part!

Thank you again for sharing your wisdom and the great experience. I wish one day I could be someone like you. I am sure everyone who is reading this book will appreciate your effort. 

P.S. Thanks for pointing out the different definitions which were used in the post, great notice!
Best,

George

**Comment by ageron** [comment]
Thanks for your kind words, I'm glad I could help! :)
