### ISSUE TITLE
Chap 3, Notebook

### ISSUE THREAD

**Issue by jbmoorhouse** [ageron/handson-ml#392]
Hi Aurélien, Thanks for producing such a detailed introduction to ML, really enjoying your work. In the accompanying notebook for chapter_03, I wonder if the following;

`mnist = fetch_openml('mnist_784', version=1, cache=True)`

could be replaced with;

`mnist = fetch_openml('mnist_784', version=1, return_X_y=True)`

Since the default for `cache` is `True` and when `return_X_y` is set as `True` , `fetch_openml()`
> returns (data, target) instead of a Bunch object. See below for more information about the 
          data and target objects.

**Comment by jbmoorhouse** [comment]
Although, I guess this would only work if the user has Scikit-Learn 0.20 since fetch_mldata doesn't include a `return_X_y` parameter.

**Comment by ageron** [comment]
Thanks @jbmoorhouse ,
Indeed, `return_X_y=True` would be nice. I'll use it in the second edition (I'd like to keep the 1st edition as close as possible to the original code).  And you're right that `cache=True` is the default, but I wanted to make it explicit.
Btw, `fetch_mldata()` does not work anymore because mldata.org is dead, so there's no need to try to be compatible with it anymore.
Thanks for your feedback!
