### ISSUE TITLE
Support for multithreading?

### ISSUE THREAD

**Issue by martynoconnor** [ageron/handson-ml#41]
Not so much an issue, but more a suggestion, I noticed while in the latter stages of the Chapter 2 end to end tutorial, that despite supporting 8 threads, the more maths intensive end of the code was only ever running on one core in my CPU. Given the complexity and size of some datasets, it may be wiser to optimise the code to spread itself across all cores available?

**Comment by ageron** [comment]
I agree, some cells take too long, it's sometimes frustrating.  Some functions support an `n_jobs` argument that you can set to have the algorithm run in parallel on multiple cores (see the solution of exercise 1 in chapter 2 for an example, where n_jobs=4). That's the simplest way to speed up the notebook. One reason I did not do that is because I wanted to keep the examples as reproducible as possible. I set a random seed everywhere so that I would always get the same output, and I limited to one CPU for that same reason (with multiple cores, I would not necessarily get the

**Comment by ageron** [comment]
Hi @martynoconnor ,
Have you tried setting n_jobs to the number of cores on your machine?  Did it improve things?
