### ISSUE TITLE
Theory Question -Precision/Recall CV

### ISSUE THREAD

**Issue by VirajVaitha123** [ageron/handson-ml#412]
I am quite new to machine learning and struggle with some of the basics. Any advice would be appreciated.

So in order to obtain the **confusion matrix** we first use **cross_val_predict**.

I understand that this is outputting the results for each CV Fold (CV =3). 

When we pass this into the confusion matrix it seems that the total number of values equates to the size of the dataset. However, shouldn't I be expecting 3xDataset size ?

I am assuming this since testing occurs on each 1/3 of the dataset that has been trained on the remaining datasets. This leads to 3 runs (permutations) in total. 

I thought that I would either have 3 separate confusion matrix for each case or a large confusion matrix with all outputs. 

Alternatively It could be, if a result was the same in each CV don't show duplicates. This means the model performed fairly consistently across each fold. I would still expect some deviation from the total dataset size.

Or I've completely misunderstood what is happening.

Thank you

**Comment by ageron** [comment]
Hi @VirajVaitha123 ,

Thanks for your question. The `cross_val_predict()` function returns a single prediction per instance in the dataset, regardless of the number of folds. Suppose there are 6 instances, and we use 3 folds. We first train on instances 1, 2, 3, 4 and use the resulting model to make predictions for instances 5 and 6. Then we train on instances 1, 2, 5, 6 and we use the resulting model to make predictions for instances 3 and 4. And finally we train on instances 3, 4, 5, 6 and we use the resulting model to make predictions for instances 1 and 2. As you can see, we made a single prediction per instance, even though we trained 3 models.

So for example, in the following code `y_train_pred` will have the exact same length as `X_train` and `y_train_5`:

```python
from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3)
```

Now on to the confusion matrix: if there are K classes, then the confusion matrix will be a K×K matrix. In row _i_, column _j_, it counts the number of instances of class _i_ that were classified as class _j_. So the sum of all values (as you noted) is equal to the total number of instances.

So, for example, in the following code, since we are dealing with a binary classification task (2 classes), the confusion matrix is 2×2. The top left cell tells use that there are 53,272 instances that were negative (not 5s), and were indeed classified as negative. The lower left cell tells use that there are 1,077 instances that were positive (5s) but were mistakenly classified as negative (these are called false negatives). The top right cell counts the false positives (the instances are actually negative, but the classifier thought they were positive). And finally the lower right cell counts the true positives (5s correctly classified as 5s):

```pycon
>>> from sklearn.metrics import confusion_matrix
>>> confusion_matrix(y_train_5, y_train_pred)
array([[53272,  1307],
       [ 1077,  4344]])
```

Note that the total sum of all the values is 60,000 which is the number of instances in the dataset.

Hope this helps!

**Comment by VirajVaitha123** [comment]
Thank you for your quick response and detailed answer it was really useful !🥇
