### ISSUE TITLE
Chapter 2 Exercise 2, log of exponential distribution

### ISSUE THREAD

**Issue by Tuna0679** [ageron/handson-ml#413]
Thanks for great work, I enjoyed your clear instruction, but the other day I bumped into this and couldn't get out:
In ex. 2 of chapter 2, you explained about the log distribution of gamma:

> Let's look at the exponential distribution we used, with scale=1.0. Note that some samples are much larger or smaller than 1.0, but when you look at the log of the distribution, you can see that most values are actually concentrated roughly in the range of exp(-2) to exp(+2), which is about 0.1 to 7.4.
These are the hist plot for the distribution of expon distribution
![image](https://user-images.githubusercontent.com/44334795/56850127-61af5680-6928-11e9-9bd2-48cfae144778.png)

Q1: Why did you assign scale = 1.0? How is this helpful? How did you come to scale=1 rather than other scale
Q2: values are concentrated between 0.1 to 7.4. how is this helpful?
Q3: Should we use reciprocal here instead? I read your explanation about the uniform of log distribution in another thread about reciprocal distribution and it is good.

Thanks very much!

**Comment by ageron** [comment]
Hi @Tuna0679 , great questions! 
Q1: it was arbitrary. The important thing to note is that sampling from this distribution will give you a fair amount of tiny values, as well as much larger values: it's good when you only know approximately what the right scale is. But you may have to tune that scale for your particular problem.
Q2: I wrote this to note that there _is_ a range of values that is favored by this distribution, it does not give you many values of scale 1e-10 for example. Similarly, it's very unlikely to go well beyond 10.
Q3: Yes, you can go for the reciprocal distribution rather than the exponential distribution if you don't know what the scale of the hyperparameter is at all. It draws the scale itself from a uniform distribution.

Finding the right scale for a hyperparameter is sometimes somewhat of a black art. But this [2018 paper](https://arxiv.org/pdf/1803.09820.pdf) proposes a more disciplined approach to hyperparameter tuning: I highly recommend you check it out. I'll try to describe this in the 2nd edition.
Hope this helps.

**Comment by Tuna0679** [comment]
Thanks, you clarified a lot of things for me. I surely going to go through the paper you recommended. Have a nice day!
