### ISSUE TITLE
Exercise Answers for Chapter 1

### ISSUE THREAD

**Issue by lachancek** [ageron/handson-ml#425]
Hi, I just finished chapter 1 of your book. Is a spam filter a supervised classification algorithm?

**Comment by ageron** [comment]
Hi @lachancek ,

Absolutely, well done! :) You could even say it's a supervised binary classification algorithm since there are just two classes. Note classification is a supervised learning task, so saying "supervised classification" is a bit redundant. You could just say "binary classification algorithm".

I hope you'll enjoy the rest of the book!

**Comment by lachancek** [comment]
Thank you Aurelion. I'm getting alot out of this book.
BTW: Does your name mean Golden Guard in French?

Thanks!

**Comment by ageron** [comment]
I'm glad you're learning a lot! :)
Aurelius was a Roman family name. In fact, there was a roman emperor by that name, Marcus Aurelius, who ruled from 161 to 180 AD. The name is derived from "aurum", which means "gold" in Latin. That's also why the chemical symbol for gold is AU. However, I have never heard about the "guard" meaning.

**Comment by lachancek** [comment]
Thank you 
I am reading Marcus Aurelius' Meditations at the moment. He was the last of the adoptive emperors and the period of peace in Rome that stretched the adoptive emperors reigns. Interesting about the Latin derivation of the name.
