### ISSUE TITLE
Chapter-3 Issue when fitting the SGD

### ISSUE THREAD

**Issue by ML-novice** [ageron/handson-ml#439]
I was trying to fit the model using SGD, I changed the code a bit because I got some index errors, when i changed the code, everything was fine except at the end, when fitting the model.
it was throwing this error.

**ValueError: Found input variables with inconsistent numbers of samples: [784, 60000]**

This is the code :

```python
import numpy as np
import pandas as pd
from sklearn import datasets
from six.moves import urllib
from sklearn.datasets import fetch_mldata
from mat_file_to_dict import loadmat
import matplotlib
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier

try:
    mnist = fetch_mldata('MNIST original')
except:
    print("Could not download MNIST data from mldata.org, trying alternative...")
    mnsit_path = r'C:\Users\bjmq6m\Documents\ML\mnist-original'
    mnist_raw = loadmat(mnsit_path)
    mnist = {
        "data": mnist_raw["data"],
        "target": mnist_raw["label"],
        "COL_NAMES": ["label", "data"],
        "DESCR": "mldata.org dataset: mnist-original",
    }


X,y = mnist['data'],mnist['target']
x_train,y_train,x_test,y_test = X[:,:60000],y[:60000],X[:,60000:],y[60000:]

shuffle_index = np.random.permutation(60000)
some_digit = X[:,36000]
image = some_digit.reshape(28,28)
plt.imshow(image,cmap=matplotlib.cm.binary)
plt.axis("off")
#plt.show()
x_train1=[]
y_train1=[]
for i in range(shuffle_index.size):
     x_train1.append(x_train[:,shuffle_index[i]]),y_train1.append(y_train[shuffle_index[i]])

x_train1,y_train1 = np.transpose(np.array(x_train1)),np.array(y_train1)

y_train_5 = (y_train1==5)
y_test_5 = (y_test==5)

data sets very effectively.
sgd_clf = SGDClassifier(random_state=42)
sgd_fit = sgd_clf.fit(x_train1,y_train_5) # **error pops at this line**

print(sgd_clf.predict(some_digit))
```

**Comment by ageron** [comment]
Hi @ML-novice ,

Thanks for your question. You should not use `fetch_mldata()` anymore, it does not work anymore because the website it relied on (mldata.org) is dead. Scikit-Learn now proposes `fetch_openml()` instead. It is not exactly a drop-in replacement, see [my comment here](https://github.com/ageron/handson-ml/issues/301#issuecomment-448853256).

Your code tries to use`fetch_mldata()`, but that fails so it falls back to loading a copy of MNIST you downloaded. However, the version you downloaded is transposed compared to the usual format. If you don't want to use `fetch_openml()`, then you should probably transpose the data immediately after loading it, then you can use the code in the book:

```python
    mnist = {
        "data": mnist_raw["data"].T, # <= transpose
        "target": mnist_raw["label"],
        "COL_NAMES": ["label", "data"],
        "DESCR": "mldata.org dataset: mnist-original",
    }
```

Then of course, this means swapping the indices in the rest of your code example, and removing the call to `tf.transpose()`.

Hope this helps.

**Comment by ML-novice** [comment]
Hi @ageron 

Thanks, it worked. I never knew the data was transposed. I was thinking the 784 pixels were stored in the columns.
