### ISSUE TITLE
chapter 2 Found input variables with inconsistent numbers of samples:

### ISSUE THREAD

**Issue by RajParab** [ageron/handson-ml#442]
While executing the linear regression i got this error 

the housing_prepared.shape is (16512, 17)

Where could I had gone wrong?

**Comment by ageron** [comment]
Hi @RajParab ,

A common mistake is to call `fit_transform()` instead of `transform()` on the test data.  You should only ever call `fit()` or `fit_*()` on training data.  If you call `fit_transform()` on the test data, it may find some categories that were not present in the training data (or conversely, it may not find all the categories that were in the training data), so it will produce one-hot encodings of a different size. I'm guessing this is what's happening.

Hope this helps.

**Comment by RajParab** [comment]
the shape difference is sorted `add_bedrooms_per_room= True` I set it to False

Now the shape of array is correct. 

But error is still persistent when I try to execute Linear Regression 

I am not getting your point because whenever I try to execute without fit, this error occurs.`This ColumnTransformer instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.`

Thanks for your help

**Comment by ageron** [comment]
Hi @RajParab ,
You should fit your model on the training set, and then use it on the new data. My point was that you should not fit the model on anything _else_ than the training data.

**Comment by RajParab** [comment]
Thank you for the help Issue has been solved

**Comment by Tessot** [comment]
Please @RajParab how did you finally resolve this. Am getting similar issue
housing_prepared.shape returns (20640, 16)
So when I try to run the code below
lin_reg.fit(housing_prepared, housing_labels)
I get the error below
ValueError: Found input variables with inconsistent numbers of samples: [20640, 16512]
