### ISSUE TITLE
virtualenv creation

### ISSUE THREAD

**Issue by Jai-GAY** [ageron/handson-ml#47]
in page 41,
$ cd $ML_PATH
$ virtualenv env

is there a typo error ? should it be virtualenv $ML_PATH ?
if no, what does env represents ?
[virtualenv usage](https://virtualenv.pypa.io/en/stable/userguide/#usage)
Where ENV is a directory to place the new virtual environment.

**Comment by Jai-GAY** [comment]
ok, got it, is an additional folder created.

**Comment by ageron** [comment]
Yes, exactly, it's just the name of the new environment.  You can name it any way you choose.

**Comment by SalmanCode** [comment]
Hey, can you mention how did you solve the issue. I keep getting the error "The path isn't specified"

**Comment by ageron** [comment]
Hi @SalmanCode ,

Thanks for your question.

The first `$` sign on each line is a common representation of the shell prompt. In other words, you should not type it, it's just a symbol which means "type any command after that on the same line in a shell". For example:

```bash
$ dir
```

Means that you must type the command `dir` in a shell (e.g., Terminal app on MacOSX, or the 'Command Prompt' program on Windows). You should not type the first `$` sign.

However, the second dollar sign in `$ cd $ML_PATH` must be typed on MacOSX or Linux. On Windows, you should type `%ML_PATH%` instead of `$ML_PATH`. This syntax asks the shell to look for an environment variable named `ML_PATH` and to replace `$ML_PATH` (or `%ML_PATH%` on Windows) with the value of this environment variable. For example, if the `ML_PATH` environment variable is equal to `/home/salman/ml`, then typing `cd $ML_PATH` will be equivalent to typing `cd /home/salman/ml`. If the environment variable is not set, then it will be replaced with an empty string. In this case, typing `cd $ML_PATH` will be equivalent to typing `cd`. On MacOSX and Linux, this will change the directory to your home directory. I'm not sure what it does on Windows. Perhaps it gives you the error "The path isn't specified".

So you have two options:
* Either replace `$ML_PATH` with the path to your ML directory every time you see `$ML_PATH`.
* Or set the `ML_PATH` environment variable. Here's [how to set an environment variable](https://www.schrodinger.com/kb/1842).

Does this help?

**Comment by SalmanCode** [comment]
I figured it out but this is helpful too. Thanks a lot for your help though.

Kind regards.
