### ISSUE TITLE
chapter 3: Problem with new threshold

### ISSUE THREAD

**Issue by FritzPeleke** [ageron/handson-ml#472]
Hi Ageron,
i am working with chapter 3 of the book now and I am having a certain message associated with my assigned threshold. I get a 0.0 Recall and an Undefinedmetrics warning for precision. Could you please help explain why and possible solution. Thanks
My code:

```python
#CLASSIFICATION....MNIST DATASET
from sklearn.datasets import fetch_openml
import matplotlib as mpl
import matplotlib.pyplot as plt
import random
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.base import  clone, BaseEstimator
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix, precision_score,recall_score,f1_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_recall_curve
random.seed = 42
mnist = fetch_openml('mnist_784')
X,y = mnist['data'],mnist['target'].astype(np.int8)

##looking at a single data to see the figure
some_digit = X[4000]
some_digit_image = some_digit.reshape(28,28)
#plt.imshow(some_digit_image,cmap=mpl.cm.binary)
#plt.axis('off')
#plt.show()

##ceating our test dataset
X_train,X_test,y_train,y_test = X[:60000],X[60000:],y[:60000],y[60000:]
schuffle_index = np.random.permutation(60000)
X_train,y_train = X_train[schuffle_index],y_train[schuffle_index]

##creating a binary classifier
y_train_5 = (y_train == 5 )
y_test_5 = (y_test == 5)
print(y[4000])

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train,y_train_5)

##Building a function that works like cross_val_score

def skfold(x_train,y_train,estimator):
    skfolds = StratifiedKFold(n_splits=3,random_state=42)
    for train_index,test_index in skfolds.split(x_train,y_train):
        clone_clf = clone(estimator)
        x_train_fold = x_train[train_index]
        x_test_fold = x_train[test_index]
        y_train_fold = y_train[train_index]
        y_test_fold = y_train[test_index]

        clone_clf.fit(x_train_fold,y_train_fold)
        y_pred = clone_clf.predict(x_test_fold)
        n_correct = sum(y_pred == y_test_fold)
        print(n_correct / len(y_pred))

'''skfold(X_train,y_train_5,sgd_clf)
#lets use sklearns.cross_val_score
score = cross_val_score(sgd_clf,X_train,y_train_5,scoring='accuracy',cv=3)
print(score)'''

class Never5Classifier(BaseEstimator):
    def fit(self,X,y= None):
        pass
    def predict(self,X,y=None):
        return np.zeros((len(X),1),dtype=bool)
'''nev_clf = Never5Classifier()
nev_score = cross_val_score(nev_clf,X_train,y_train_5,cv=3,scoring='accuracy')
print(nev_score)'''
#confusion matrix,precision,recall and f1_ score
y_pred = cross_val_predict(sgd_clf,X_train,y_train_5,cv=3)
conf_matrix = confusion_matrix(y_train_5,y_pred)
print(conf_matrix)
print(precision_score(y_train_5,y_pred))
print(recall_score(y_train_5,y_pred))
print(f1_score(y_train_5,y_pred))

#Finding which threshhold to use for prediction(plotting precision_recall_curve)

y_scores = cross_val_predict(sgd_clf,X_train,y_train_5,cv=3,method='decision_function')
precision, recall, threshold = precision_recall_curve(y_train_5,y_scores)


def plot_prec_recall_vs_threshold(precision,recall,threshold):
    plt.plot(threshold,precision[:-1],"b--",label= 'precision')
    plt.plot(threshold,recall[:-1],'g-',label='recall')
    plt.xlabel("Threshold")
    plt.legend(loc = 'center left')
    plt.ylim([0,1])


#plt.plot(recall,precision)
print('new precision and recall based on threshold')
y_score_90 = (y_scores > 70000)
prec = precision_score(y_train_5,y_score_90)
print(prec)
```

Output:

```
C:\Users\fritz\Hello\Scripts\python.exe C:/Users/fritz/PycharmProjects/Hello/Handson-ML-C3.py
7
[[53292  1287]
 [  936  4485]]
0.777027027027027
0.8273381294964028
0.8013937282229965
new precision and recall based on threshold
C:\Users\fritz\Hello\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
0.0
  'precision', 'predicted', average, warn_for)

Process finished with exit code 0
```

**Comment by ageron** [comment]
Hi @FritzPeleke ,

Thanks for your question. Looking at your code:

* the random module is not used (import random is not neeeded)
* `random.seed` is a function. You should write `random.seed(42)`, not `random.seed = 42`. But it's not used anyway in this code, since Scikit-Learn and NumPy use NumPy's random number generator (`np.random`). You could run `np.random.seed(42)`.
* the `skfold()` function is unused.
* the `Never5Classifier` class is unused.
* the value 70000 used to define `y_score_90` is incorrect, it should be defined like this:

```python
y_score_90 = threshold[np.argmax(precision >= 0.90)]
```

Then everything works fine. :)

What happened is that the random seed was not set properly, so the code did not run exactly the same way as in the book, and thus the threshold of 70,000 was not correct. In fact, this threshold ended up being higher than the highest threshold, so there were no positive predictions, and thus precision could not be computed (since it is the ratio of true positives divided by the number of positive predictions, but since there's no positive predictions, it's undefined).

So you should either run the exact same code as in the notebook (including setting the random seed the same way), or you should define the threshold dynamically, based on the distribution of precisions depending on the thresholds. Let me explain `threshold[np.argmax(precision >= 0.90)]`:

* The `precision` array contains increasing precisions (since the threshold increases), except perhaps close to the end of the array, but we can ignore that (see the note immediately after figure 3-4 in chapter 3).
* So `precision >= 0.9` will contain a bunch of `False` values followed by a bunch of `True` values (plus a few `False` near the end, but we can ignore that). The threshold at which the values change from `False` to `True` corresponds to precision 90%.
* `np.argmax(precision >= 0.90)` gives the index of the max value in an array (or the index of the first occurrence of the max value if it is repeated several times). The value `True` is considered larger than `False`, so this will give us the index of the first `True` value in the array `precision >= 0.9`. In other words, it's the index of the threshold that gives precision 90% (or close enough).
* So `threshold[np.argmax(precision >= 0.90)]` is the threshold that gives the precision closest to 90% (or slightly above it).

I hope this helps.

**Comment by FritzPeleke** [comment]
Hi Ageron, thanks for your reply. 
I commented out the skfold block of code because I thought the aim was to learn how to manually create something that works like cross_val_score. After creating and testing it, I saw it worked so I decided to comment it out because I was using the cross_val_score thereafter.

Before I got your response I went to the precision, recall vs threshold curve I obtained and zoomed in to get the threshold that gives me 90% precision and I did get it but not 70,000. What I got was way less than it. :(
-When I set the np.random.seed(42) I now get reproducible outputs. This is cooler than before.
-However, using threshold[np.argmax(precision >= 0.90)] is giving  an error:

Traceback (most recent call last):
  File "C:/Users/fritz/PycharmProjects/Hello/Handson-ML-C3.py", line 90, in <module>
    print(precision_score(y_train_5,y_scores_90))
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\metrics\classification.py", line 1569, in precision_score
    sample_weight=sample_weight)
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\metrics\classification.py", line 1415, in precision_recall_fscore_support
    pos_label)
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\metrics\classification.py", line 1239, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\metrics\classification.py", line 71, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\utils\validation.py", line 201, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\utils\validation.py", line 201, in <listcomp>
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "C:\Users\fritz\Hello\lib\site-packages\sklearn\utils\validation.py", line 146, in _num_samples
    " a valid collection." % x)
TypeError: Singleton array 3214.5843500411324 cannot be considered a valid collection.

**Comment by FritzPeleke** [comment]
Hi @ageron,
I finally got it. We had to do this :
threshold_at_90 = threshold[(precision >= 0.90)]
y_score_90 = (y_score > threshold_at_90)
That gets me the threshold for a precision close to or slightly above 90%.
Thanks :)
