### ISSUE TITLE
break down of the line of code 

### ISSUE THREAD

**Issue by yashGuleria** [ageron/handson-ml#477]
Hi Aurélien (or anyone who is seeing this message),

Can you please elaborate on the meaning of this line of code  
```python
reorder_train = np.array(sorted([(target, i) for i, target in enumerate(mnist.target[:60000])]))[:, 1]
```

I realize it is simple but as a beginner im having a tough time understanding it.
Thanks in advance

**Comment by ageron** [comment]
Hi @yashGuleria ,
Thanks for your question, and sorry for the late response.

Here are the following tools you need to understand this line of code (you probably know most of this, but just to be clear):
* `[10*x for x in range(5)]` will return `[0, 10, 20, 30, 40]`. This syntax is called "list comprehension". It is equivalent to the following code (except it returns the list directly, without having to create a `result` variable):

```python
result = []
for x in range(5):
    result.append(10*x)
```

* `for index, value in enumerate([10, 20, 30])` will iterate over the list `[10, 20, 30]`, but thanks to `enumerate()` il will also give each element's index. So it's like iterating over: `[(0, 10), (1, 20), (2, 30)]`.

* `sorted([5, 3, 9, 1])` will return `[1, 3, 5, 9]`, the sorted list.

* Tuples are sorted first by the first element, then the second, and so on, so `sorted([(5, 2), (4, 5), (4, 2)])` returns `[(4, 2), (4, 5), (5, 2)]`.

* `arr[:60000]` is equivalent to `arr[0:60000]`: it returns the first 60,000 elements of the array `arr`.

* `arr[:, 1]` works if `arr` is a NumPy array with (at least) 2 dimensions. It returns an array containing all the values of the second column of `arr` (index 1 = second column). For example, if `arr` is `np.array([[10, 20, 30], [40, 50, 60]])` (a 2D array with 2 rows and 3 columns), then `arr[:, 1]` is `np.array([20, 50])`.

With that in mind, you can verify that the line does the following:
* it grabs the first 60,000 targets in the MNIST dataset (`mnist.target[:60000]`). For example: `[7, 5, 1, ...]`.
* it gets their indices (`enumerate(...)`). For example `[(0, 7), (1, 5), (2, 1), ...]`.
* it uses a list comprehension to put the target first, and the index second in each tuple. For example: `[(7, 0), (5, 1), (1, 2), ...]`.
* it sorts the result, so all the indices get sorted by targets. First all the indices of the images of class 0, then all the indices of the images of class 1, and so on. For example: `[(0, 4), (0, 15), (0, 17), ...]`.
* Finally, it creates a NumPy array with the result and keeps only the second column `np.array(...)[:, 1]`. This drops the first column (the targets), keeping only the indices.

In the end, we have a 1D Numpy array containing the indices of all the images in the MNIST dataset, sorted by target. This is useful because the old methods to load the MNIST dataset used to load the dataset sorted this way, but the new methods don't. So in order to get the exact same results as the ones shown in the book, we need to reorder the MNIST dataset.

I hope this is all clear!

**Comment by yashGuleria** [comment]
Hi @ageron,
Thank you for such a detailed reply (i literally felt it was a beautiful explanation). I completely understood it.
regards
