### ISSUE TITLE
Never5Classifier is not making sense

### ISSUE THREAD

**Issue by maagalamharsha** [ageron/handson-ml#497]
Hi I was going through Chapter 3 of the book. And I am not able to understand how Never5Classifier is working. I know that it needs to detect !=5 but the syntax doesnt contain any `sgd_clf` code inside the class.

Please help me understand the operation of this class especially the syntax part of the code.

Thank you

**Comment by ageron** [comment]
Hi @maagalamharsha ,
Thanks for your question. The `Never5Classifier` is just a toy classifier which always predicts `False` (meaning "not a 5"), without even looking at the image. The goal is to demonstrate that even such a bad classifier (which doesn't learn anything at all and doesn't even look at the images) can get pretty good accuracy if most images are _not_ 5s.

For example, since about 90% of the images are NOT 5s, then the `Never5Classifier` will get about 90% accuracy. Indeed, about 90% of the time its prediction will be correct: the image is NOT a 5 and it will output `False` (which means "not a 5" in this case). But when it is shown a 5, it will still output `False` and that's when it will be wrong.

Regarding the syntax:

```python
class Never5Classifier(BaseEstimator):
    def fit(self, X, y=None):
        pass
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)
```

First we create the `Never5Classifier` class by inheriting from the `BaseEstimator` class. Then we define the `fit()` method, which has 2 arguments: the inputs `X`, and the (optional) labels `y` (plus `self`, like all instance methods). This method should usually train the model and `return self`, but in this case we're not even going to call it since there's really no training at all, so we just do nothing (`pass`). It would probably be better to `self` instead, since some Scikit-Learn components expect the `fit()` method to return `self` (for example Pipelines). In this case it does not matter since we don't call the `fit()` method anyway, as there's no training.

Then we define the `predict()` method, which takes one argument `X`: the images for which the classifier must make predictions. However, in this toy classifier, we don't even use `X` at all! We just return an array full of `False` values (one for each input image). For this we use `np.zeros()`, which returns a NumPy array full of zeros, of the desired shape. In this case, the shape is `(len(X), 1)`, which is the shape of a column vector (i.e., a matrix with a single column) of the same length as `X`. We set the `dtype` to `bool` to convert each `0` to the value `False`.

I hope this all makes sense.

**Comment by maagalamharsha** [comment]
So basically what we are doing is we are making an array of `len(x)` of `False` and `y_train_5` will have `True` where ever there is a 5. So `False` from `len(x)` and `y_train_5` will match resulting in about 90% accuracy. And when `False` from `len(x)` and a `True` from `y_train_5` results in a mismatch.

Yeah I think I got it. Close it if my understanding is a `True` :)

**Comment by ageron** [comment]
I think you got it, cool! Hope you're enjoying the book. 👍
