### ISSUE TITLE
Create the Workspace

### ISSUE THREAD

**Issue by SM-Fahim** [ageron/handson-ml#519]
There are two lines and I don't understand them. Please explain in detail, I'm a very new Linux user.
$ export ML_PATH="$HOME/ml"
$ mkdir -p $ML_PATH

Secondly, I made a folder on my desired destination. Then opened the terminal there, and typed these commands. And nothing seemed happen. The command line just skipped to get a new command.

**Comment by ageron** [comment]
Hi @SM-Fahim ,

Thanks for your questions!

The first `$` sign on each line is just there to indicate that the rest of the line is a command that should be typed in a shell (i.e., a Terminal window running a shell program such as Bourne Again Shell = bash, or zsh). Do not type the first `$` on each line.

The `export` keyword is used in a shell to define an environment variable. In this case, we are defining the `ML_PATH` environment variable to be equal to the value of the `HOME` environment variable followed by `/ml`. The `HOME` env variable is usually automatically defined by your system to be equal to the path to your home directory, which is typically `/home/your_login`.  So typically the first line will result in defining the env variable `ML_PATH` to be equal to `/home/your_login/ml` (or `/Users/your_login/ml` on MacOSX).

The second line uses the `mkdir` command to create the directory whose name we just defined in the `ML_PATH` environment variable. The `-p` option says that the command should create any parent directory that does not exist yet. For example, suppose that there's no directory called `/a`, then the command `mkdir -p /a/b/c` would create three directories: `/a`, then `/a/b` inside it, and finally `/a/b/c` inside it.

Regarding your second point: the first command will not return any output, it just defines the environment variable, so it's normal not to get any output. Similarly, the second command creates a directory and it does not give any output if it is successful. If the directory already exists, it does nothing at all.

I hope this helps!

**Comment by TrungBui-Purdue-5913** [comment]
Hi, I have just start on the book and I dont know much about the command on terminal for macbook. Do you recommend any resource to learn those command line ? Thank you

**Comment by ageron** [comment]
Hi @TrungBui-Purdue-5913 ,
Thanks for your question.  There are plenty of tutorials online, as blog posts or YouTube videos. Here's one that looks good (I haven't watched it but it's got a lot of likes): https://www.youtube.com/watch?v=aKRYQsKR46I
Hope this helps.

**Comment by bhavinmoriya** [comment]
Hi,
Why do I need to define environment variable? And that to like $HOME/ml?

**Comment by ageron** [comment]
Hi @bhavinmoriya ,

You don't have to define an environment variable for ML_PATH, you can instead write the path itself every time you need it. But if it's a long path, or if you ever want to change it, it will be more convenient to use an environment variable.

It's just like in a program: rather than repeating the same value over and over in the program, which is error prone and makes it harder to change that value later on, it's better to first define a variable equal to that value, then use the variable in the rest of the program.

Moreover, standard variables like HOME (on Linux or MacOS) also make it possible to write scripts that will write to the user's home directory, without knowing where that directory actually is when you're writing the script: all you need to know is that the HOME environment variable will point to the right location when the user runs your script. In this case, the HOME environment variable acts a bit like an input parameter for the script. Inputs could alternatively be passed as arguments on the command line, but for values that rarely change for a given user, such as the HOME directory, it's more convenient to use environment variables.

 Hope this helps.

**Comment by bhavinmoriya** [comment]
> Hi @bhavinmoriya ,
> 
> You don't have to define an environment variable for ML_PATH, you can instead write the path itself every time you need it. But if it's a long path, or if you ever want to change it, it will be more convenient to use an environment variable.
> 
> It's just like in a program: rather than repeating the same value over and over in the program, which is error prone and makes it harder to change that value later on, it's better to first define a variable equal to that value, then use the variable in the rest of the program.
> 
> Moreover, standard variables like HOME (on Linux or MacOS) also make it possible to write scripts that will write to the user's home directory, without knowing where that directory actually is when you're writing the script: all you need to know is that the HOME environment variable will point to the right location when the user runs your script. In this case, the HOME environment variable acts a bit like an input parameter for the script. Inputs could alternatively be passed as arguments on the command line, but for values that rarely change for a given user, such as the HOME directory, it's more convenient to use environment variables.
> 
> Hope this helps.

HI @ageron 
Thank you very much for the detailed description of the problem. It made the problem extremely clear to me. I would like to say thanks for the wonderful book too.
regards,
