### ISSUE TITLE
Can't download MNIST_784

### ISSUE THREAD

**Issue by tangwxxxxxxx2126** [ageron/handson-ml#626]
i have tried many codes in this issues part,but no one works.Maybe due to im in China,the network dont support me to visit that website.
There is the error info:   The remote host forced an existing connection to be shut down by the remote host. >
Could u give me some method to solve it...Or upload the "mnist_784" file to GitHub?
last, thanks for ur help

**Comment by tangwxxxxxxx2126** [comment]
@ageron

**Comment by ageron** [comment]
The error looks like it's a network issue. This could be due to a firewall, or a proxy misconfiguration, or just a WiFi coverage problem, for example.

If it's a firewall issue, you may be able to work around it using a VPN.

Alternatively, you could try downloading the data from another source. Here are a few ways to download MNIST:

Using Keras:

```python
from tensorflow import keras
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()
```

Using Scikit-Learn:

```python
from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784", as_frame=False)
X_train, X_test = mnist.data[:60000], mnist.data[60000:]
y_train, y_test = mnist.target[:60000], mnist.target[60000:]
```

You could also try using the `mnist` library (`pip install mnist`), which downloads the data from Yann LeCun's website (unfortunately, it seems to be down right now, so I'm not sure how reliable this solution is):

```python
import mnist

X_train = mnist.train_images()
y_train = mnist.train_labels()
X_test = mnist.test_images()
y_test = mnist.test_labels()
```

There are also various mirrors of this dataset, for example in this github repository: https://github.com/cvdfoundation/mnist

Hope this helps (closing, as this seems like a client-side issue).

**Comment by tangwxxxxxxx2126** [comment]
My problem is solved.Thanks for your respond.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ageron/handson-ml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ageron/handson-ml] Can't download MNIST_784 (#626)





 
The error looks like it's a network issue. This could be due to a firewall, or a proxy misconfiguration, or just a WiFi coverage problem, for example.
 
If it's a firewall issue, you may be able to work around it using a VPN.
 
Alternatively, you could try downloading the data from another source. Here are a few ways to download MNIST:
 
Using Keras:
 from tensorflow import keras (X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()
 
Using Scikit-Learn:
 from sklearn.datasets import fetch_openml mnist = fetch_openml("mnist_784", as_frame=False) X_train, X_test = mnist.data[:60000], mnist.data[60000:] y_train, y_test = mnist.target[:60000], mnist.target[60000:]
 
You could also try using the mnist library (pip install mnist), which downloads the data from Yann LeCun's website (unfortunately, it seems to be down right now, so I'm not sure how reliable this solution is):
 import mnist X_train = mnist.train_images() y_train = mnist.train_labels() X_test = mnist.test_images() y_test = mnist.test_labels()
 
There are also various mirrors of this dataset, for example in this github repository: https://github.com/cvdfoundation/mnist
 
Hope this helps (closing, as this seems like a client-side issue).
