### ISSUE TITLE
colorbar labels in Ch 02 example may be wrong

### ISSUE THREAD

**Issue by denisfitz57** [ageron/handson-ml#65]
I don't think the block of code starting with:

import matplotlib.image as mpimg

assigns the colorbar labels correctly.  It seems to me that the tick values must also be set appropriately, though I'm not sure how to do that.

**Comment by ageron** [comment]
Hi @denisfitz57 , thanks for your feedback.
I'll investigate this as soon as I get back from vacation next week.

**Comment by ageron** [comment]
Wow, I've just wrestled against this issue for over an hour, and I can't find a way to make it display nicely using the latest Matplotlib library (it used to work fine with the previous Matplotlib library, since that's how I generated the image in the book, which looks okay).
I have tried to use the following code, but no ticks or labeled are displayed:
```
cbar = plt.colorbar()
cbar.set_ticks(tick_values)
cbar.set_ticklabels(["$%dk"%(round(v/1000)) for v in tick_values])
```
It seems that its boundaries are incorrect.  If I set `boundaries=[0, 500000]` when creating the colorbar, I see nice ticks and labels, but then the colorbar itself is all yellow.  I think the colorbar is based on the pixel values in the image instead of the values in the scatterplot. Not sure why, so I'll need a bit more time to investigate.

**Comment by akjain90** [comment]
hi,
Any updates on this issue?

**Comment by ageron** [comment]
Hi @akjain90 , unforunately no update: I spent another 20 minutes on this without success.  If anyone has an idea, I'd be very grateful.

**Comment by MostafaKhezri** [comment]
@ageron When I saw that the colorbar colors evidently don't match the scatter plot, I fixed this issue by doing the following:
Just plot the image with the same `cmap` argument as the scatter plot: 
` plt.imshow(california_img, extent=[-124.55, -113.80, 32.45, 42.05], alpha=0.5, cmap=plt.get_cmap("jet"))`
This does not change the displayed California image, but tells the `colorbar` to use the same colormap as the scatter plot.

**Comment by ageron** [comment]
Thanks a lot Mostafa, I'll try this out asap.

**Comment by nkoronka** [comment]
Thanks Mostafa, worked a charm :)
