### ISSUE TITLE
ImportError: cannot import name 'fetch_mldata' from 'sklearn.datasets' (F:\Anaconda3\lib\site-packages\sklearn\datasets\__init__.py)

### ISSUE THREAD

**Issue by jltxwxj** [ageron/handson-ml#657]

**Comment by ageron** [comment]
Hi @jltxwxj ,

The `fetch_mldata()` function was removed 3 or 4 years ago, because the website it relied on was no longer maintained.
It was replaced with `fetch_openml()`, which relies on the well-maintained openml.org website.
See [this issue #301](https://github.com/ageron/handson-ml/issues/301#issuecomment-448853256) for more details.

Also note that `fetch_openml()` changed recently, so in the latest versions of Scikit-Learn, you will need to add the argument `as_frame=False` to ensure that the code examples still work.

Lastly, the 1st edition of my book is becoming a bit old now. The 2nd edition was released in 2019, and the 3rd edition is coming out soon. The early release is already [available here](https://homl.info/er3). And the up-to-date code is in the github.com/ageron/handson-ml3 repository.

Hope this helps!
