### ISSUE TITLE
Parentheses around assignment on cross-validation in Ch. 3

### ISSUE THREAD

**Issue by wmbuchanan** [ageron/handson-ml#67]
Hello. I'm sorry to bother with what is probably a trivial question. I'm wondering, in the boxed section on page 83, **Implementing Cross-Validation**, there are lines like,

`X_train_folds = X_train[train_index]`
`y_train_folds = (y_train_5[train_index])`

I've been searching around online, and experimenting with the syntax on my own, but I can't seem to figure out what the parentheses are doing in the second line. What are they for?

Thanks for humoring me!

**Comment by ageron** [comment]
Hi @wmbuchanan ,

Thanks for your question.  There's really no reason to have these parentheses, I have no idea why they are there (but they don't hurt, they just do nothing at all).  I just removed them and I'll push these changes shortly.

I sometimes add parentheses for clarity, for example:

```python
is_million = (price == 1000000)
```

The parentheses can be removed since the `==` operator has higher precedence, but I find the resulting code a bit unclear:

```python
is_million = price == 1000000
```

Cheers,
Aurélien
