### ISSUE TITLE
tf.Saver.save() not working as expected

### ISSUE THREAD

**Issue by wmbuchanan** [ageron/handson-ml#68]
The line `save_path = saver.save(sess, "/tmp/my_model.ckpt")` in Chapter 9 does not result in any files being written (at least for me). This can be solved by removing the first `/` from the path.

The other issue is that this method does not actually write a file called `my_model.ckpt`. Instead, it writes files like `my_model_final.ckpt.index`, `my_model_final.ckpt.meta`, and `my_model.ckpt.data-00000-of-00001`.

A source on StackOverflow says to instead create a `saver` using `saver = tf.train.Saver(write_version=tf.train.SaverDef.V1)`, though this results in a warning that the method has been deprecated.

What do you suggest as the best way to handle this?

**Comment by wmbuchanan** [comment]
Alright, so it seems for my first issue, the `/` at the beginning was causing it to consider `/tmp/my_model.ckpt` the _entire_ path, so it was saving the files in a directory called `tmp` directly on my hard drive. Removing the `/` put `tmp` in my `ml` folder.

As for the other issue, I believe the best thing to do is to save with this syntax: `save_path = saver.save(sess, "/tmp/my_model")`, and to restore with this syntax: `saver.restore(sess, save_path)` (rather than hard coding in your path)

**Comment by ageron** [comment]
Hi @wmbuchanan ,

Thanks for your feedback.  Indeed, the `save()` method takes either an absolute path (starting with a /) or a relative path (without the leading /), as you figured out.  On Linux & MacOS, the `/tmp` directory exists and is typically used to save temporary stuff, but you can use any other path you choose.

The `save()` method actually saves multiple files, as you noticed, and names them by appending various suffixes at the end of the provided path (such as `.index`, `.meta`, etc.).  Since the `save()` method returns the base path, you can indeed use this to avoid hard-coding paths all over the place.
