### ISSUE TITLE
Chapter 3 - MNIST data not available

### ISSUE THREAD

**Issue by Jeronimo-GL** [ageron/handson-ml#7]
The issue is already open in the scikit-learn repo. But maybe you can help with it.

https://github.com/scikit-learn/scikit-learn/issues/8588

http://mldata.org/ is down for more than a week now and sklearn code cannot download the MNIST data anymore.

Is there any alternative site to get it?.

**Comment by ageron** [comment]
Thanks for heads up, I'll look into this.

**Comment by ageron** [comment]
Alternatively, you can use TensorFlow:

```
>>> from tensorflow.examples.tutorials.mnist import input_data
>>> mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

```

**Comment by Jeronimo-GL** [comment]
Thanks!.

Great book, I forgot to mention.

2017-03-27 18:33 GMT+02:00 Aurélien Geron <notifications@github.com>:

**Comment by ageron** [comment]
I'm glad you enjoy it!  :)

Apparently, the admins of mldata.org are working on fixing the problem.  Hopefully, everything should be back to normal within the next few days.

**Comment by ageron** [comment]
Mmh, in fact after some investigation, it seems that mldata.org was managed by the European Union's PASCAL2 project, which was closed a couple years ago. The people in charge of these servers probably have some other jobs now, so it might take another few days. If this lasts too long, I'll update the book and the Jupyter notebooks.

**Comment by ageron** [comment]
Ok, I just pushed a workaround in the notebooks that use `fetch_mldata()` (chapters 3, 7, 8 and 13).

Not very pretty, but it works... as long as github.com doesn't go down and amplab/datascience-sp14 does not remove the data.

```
from six.moves import urllib
from sklearn.datasets import fetch_mldata
try:
    mnist = fetch_mldata('MNIST original')
except urllib.error.HTTPError as ex:
    print("Could not download MNIST data from mldata.org, trying alternative...")

    # Alternative method to load MNIST, if mldata.org is down
    from scipy.io import loadmat
    mnist_alternative_url = "https://github.com/amplab/datascience-sp14/raw/master/lab7/mldata/mnist-original.mat"
    mnist_path = "./mnist-original.mat"
    response = urllib.request.urlopen(mnist_alternative_url)
    with open(mnist_path, "wb") as f:
        content = response.read()
        f.write(content)
    mnist_raw = loadmat(mnist_path)
    mnist = {
        "data": mnist_raw["data"].T,
        "target": mnist_raw["label"][0],
        "COL_NAMES": ["label", "data"],
        "DESCR": "mldata.org dataset: mnist-original",
    }
    print("Success!")
```

**Comment by anhduc2203** [comment]
I tries alternative but it announce error:
  File "<ipython-input-7-b17bc527bce8>", line 2
    mnist_alternative_url = "https://github.com/amplab/datascience-sp14/raw/master/lab7/mldata/mnist-original.mat"
    ^
IndentationError: unexpected indent

**Comment by ageron** [comment]
Hi @anhduc2203 ,
That's an indentation error.  Make sure this line is indented like the rest of the block it belongs to.  [This tutorial](https://www.python-course.eu/python3_blocks.php) explains more.

**Comment by gig67** [comment]
Aurelien, yours is a great book and I am going through all the exercises.
So I got stuck here, as others. My suggestions would be to download the data from https://github.com/amplab/datascience-sp14/raw/master/lab7/mldata/mnist-original.mat 
into a local directory and then

**Comment by TomGauss** [comment]
Hi all, 

  Thanks for the great book and the advice above. This is 2019 and this is still a problem. I would like to put my solution here so others might use it. 

Aurelien, your solution above has some issues, as MAC would return an error "TimeoutError: [Errno 60] Operation timed out", because the website is down. I also agreed with gig67 that we do not need to download dataset every time unless we have to. Therefore, I simply combined them together here:

`from six.moves import urllib
from sklearn.datasets import fetch_mldata

#try different solutions from here
#https://github.com/ageron/handson-ml/issues/7
#the try code below would return operation timed out as the web is down
#try to import data
    # Alternative method to load MNIST, if mldata.org is down
from scipy.io import loadmat
def data_down():
    mnist_alternative_url = "https://github.com/amplab/datascience-sp14/raw/master/lab7/mldata/mnist-original.mat"
    mnist_path = "./mnist-original.mat"
    response = urllib.request.urlopen(mnist_alternative_url)
    with open(mnist_path, "wb") as f:
        content = response.read()
        f.write(content)
    return mnist_path

#run this if it is the first time or you need to update
# mnist_path = data_down()

#since we already download the dataset, we could directly use them
mnist_path = "./mnist-original.mat"
mnist_raw = loadmat(mnist_path)
mnist = {
    "data": mnist_raw["data"].T,
    "target": mnist_raw["label"][0],
    "COL_NAMES": ["label", "data"],
    "DESCR": "mldata.org dataset: mnist-original",
    }
print("Success!")`

So now we could download the data first time we use, and stick on it during the analysis, and update if needed in future.

**Comment by ageron** [comment]
Hi @TomGauss , thanks for your message. `fetch_mldata()` is now deprecated and it has been replaced with `fetch_openml()`.  See my comments in #301 for more details.
