### ISSUE TITLE
DNN classifier example produces blue screen of death every time.

### ISSUE THREAD

**Issue by Bazman76** [ageron/handson-ml#79]
Hi,

When running inputs 9 10 and 11 from the below notebook, I get a blue screen of death every time? 

https://github.com/ageron/handson-ml/blob/master/10_introduction_to_artificial_neural_networks.ipynb

I'm using:
Python ver 3.5.3
Tensorflow 1.2.1
Running on a windows 7 pro machine.

Any tips on how to resolve this?

**Comment by ageron** [comment]
Hi @Bazman76 ,
Wow, that's pretty bad. When a BSOD occurs, it is almost always one of 3 things: a bug in some low-level library (e.g., device drivers), incompatible low-level libraries (for example, a library for hardware A installed on hardware B, or a library C that relies on library D version X, but instead version Y is installed), or finally a hardware failure (e.g., a faulty RAM).
Unfortunately, I haven't used Windows over the last 15 years, so I'm afraid I can't help you.  All I can say is that it's definitely not a problem in the code (it works for myself and everyone else, AFAIK), and it is probably not a TensorFlow issue either, because even if it has a bug in it, it should not cause a BSOD.
If you agree, please close this issue, and try to get help from the TensorFlow team (in case it's a known issue on their end), or a Windows support list.
Sorry I can't help you out more than that.
Cheers,
Aurélien

**Comment by Bazman76** [comment]
Apparently Tensorflow for windows is generally pretty buggy relative to the linux version!
Also the code example is based on tf.contrib which can be subject to changes.
Thanks anyway I'm really enjoying the book.
