### ISSUE TITLE
ch3: dimension of the y_scores generated by cross_val_predict()

### ISSUE THREAD

**Issue by Capsuley** [ageron/handson-ml#81]
Hi, Aurélien, thank you for this great book!

Everything goes well until this y_scores dimension issue:
`y_scores = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3,
                             method="decision_function")
y_scores`

Any input error will occur when the codes below are executed, and I'll have to slice the y_scores (with first line being all '0') to generate everything for the plot.

`from sklearn.metrics import precision_recall_curve

precisions, recalls, thresholds = precision_recall_curve(y_train_5, y_scores[:,1])`

Could you help me out of this?

Thank you.

**Comment by cleuton** [comment]
I've got the same problem.

**Comment by cleuton** [comment]
Also, I am having error running the following code:
```
y_train_pred_90 = (y_scores > 70000)
precision_score(y_train_5, y_train_pred_90)
recall_score(y_train_5,y_train_pred_90)
```
ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets

**Comment by Freyert** [comment]
Riiight, looks like I have the same problem, too. Another `sklearn 1.19` thing perhaps?

```
y_scores = cross_val_predict(sgd_clf, X_train, y=y_train_5, cv=3,
                             method="decision_function")
y_scores

array([[       0.        ,  -281758.48589183],
       [       0.        ,  -417371.34963741],
       [       0.        ,  -426408.90703819],
       ..., 
       [       0.        ,  -602124.59376402],
       [       0.        ,  -816007.64790856],
       [       0.        , -1484384.8040138 ]])
```

So yes, it is producing a 2 dimensional array, but why?

**Comment by Capsuley** [comment]
@Freyert Maybe this is the new mechanism that I don't know and put [:, 1] will fix this.

ALso, according to https://github.com/scikit-learn/scikit-learn/issues/9587, there is another problem about the latest version of pipeline, which will raise the TypeError in ch4 about tuple not supported.

**Comment by CharlesFr** [comment]
Has anyone managed to deal with this issue?

ValueError: Classification metrics can't handle a mix of binary and multilabel-indicator targets

**Comment by ageron** [comment]
Hi everyone,

My apologies for the delayed answer, I was quite busy lately.

I looked into these issues:
* the `cross_val_predict()` issue is actually due to a [bug in Scikit-Learn 0.19](https://github.com/scikit-learn/scikit-learn/issues/9589) which adds an extra first dimension to the result, for no good reason.  I added a workaround in the notebook, you can take a look if you want (basically I drop the first dimension if I see that the result has two dimensions).
* In Scikit-Learn 0.19, `Pipeline`s now refuse tuples of tuples, they want lists of tuples. Sigh. I updated the notebooks accordingly.
* Also, `LabelBinarizer` no longer works in pipelines. Granted, it was never designed for handling input features, only labels.  The correct solution will be to use `OneHotEncoder` once it supports strings as categorical input features (they're working on it). In the meantime, I have just created a small subclass that changes the signature of the `fit_transform()` method, and everything works fine (ugly, but it works).

I'm going through all notebooks right now with the latest versions of every library, so far these are the only issues I have found, but I still have a few notebooks to run.

Hope this helps!

**Comment by ageron** [comment]
After some more input from @dustbort and @amueller (thanks!), I decided that keeping the `LabelEncoder` and `LabelBinarizer` was not a good idea, even if I explicitely pointed out that it was a temporary workaround. There were a few other options, including Pandas' `factorize()` or `get_dummies()` functions, but I chose to use instead the `CategoricalEncoder` class, even though it is not part of Scikit-Learn yet (see scikit-learn/scikit-learn#9151), because it's the cleanest solution to use in a `Pipeline`.  I updated the notebook for chapter 2, you can take a look if you're interested.

**Comment by ageron** [comment]
Closing this issue. Thanks again for your feedback, it was really helpful.  Please reopen if the problem persists.
