### ISSUE TITLE
Chapter 2 - Create the workspace

### ISSUE THREAD

**Issue by sa1lor** [ageron/handson-ml#89]
First off many thanks for the book, I look forward to use it.

I have some issues right at the start of Chapter 2. The commands are simply not working for me from page 40 to 42 (I havent even got to the later pages). I have both Anaconda (so I am running windows) with Spyder/Ipython and Jupyter notebook installed (downloaded for a Python coursera course) and downloaded also Python 3.6 separately today, however the commands give me syntax error irrespectively of what I am using. The $ prompt (which I am not able to google for python and havent seen in any examples, though I am rookie) gives back an invalid syntax msg so is pip3 undefined. 

Could someone tell me what am I doing wroing?

Thanks.

**Comment by jasrys** [comment]
The $ prompt is usually your shell prompt. You want open a Jupyter Notebook (try typing `jupyter notebook` at the $ prompt) and run the python commands in the notebook

**Comment by ageron** [comment]
Hi @sa1lor ,
Anaconda is a package that contains Python + some scientific libraries, including NumPy, Matplotlib and Jupyter, plus a packaging system.  If you choose to use Anaconda, then you must use its packaging system to install the few missing libraries (e.g., TensorFlow): the packaging system command is `conda` (not `pip3`).
Alternatively, you can choose to use "plain" Python 3.6 and use its packaging system (pip3) to install all the libraries.  I personally prefer this solution, in part because I'm used to it, and also because it's easier to get the latest version of libraries I'm interested in.  If you get an error saying that `pip3` is an unknown command, it probably means that you should add Python 3.6 to your `PATH`.
Try going through the instructions on the [home page](https://github.com/ageron/handson-ml).
As @jasrys mentionned, the `$` just represents a terminal prompt: you should not type it, only whatever is shown after it. 
If you still experience problems with the installation, please copy/paste the full error messages.
Hope this helps.

**Comment by sa1lor** [comment]
Thank you both!
